Repository openDAQ/openDAQ, pull requests merged in 2023-12, with the labels that each got.

#35 [TBBAS-597] support vector by renderer
  core/opendaq/reader/src/typed_reader.cpp
  core/opendaq/signal/include/opendaq/data_packet_impl.h
  examples/cpp/quick_start/quick_start_full.cpp
  modules/ref_fb_module/include/ref_fb_module/classifier_fb_impl.h
  modules/ref_fb_module/include/ref_fb_module/renderer_fb_impl.h
  modules/ref_fb_module/src/CMakeLists.txt
  modules/ref_fb_module/src/classifier_fb_impl.cpp
  modules/ref_fb_module/src/ref_fb_module_impl.cpp
  modules/ref_fb_module/src/renderer_fb_impl.cpp
  modules/ref_fb_module/tests/test_ref_fb_module.cpp
  modules/tests/test_ref_modules/classifier_test_helper.h
  modules/tests/test_ref_modules/test_ref_modules.cpp
Labels: enhancement

#59 Replace weak reference in property_object_class builder interface
  bindings/python/core_objects/generated/py_property_object_class_builder.cpp
  changelog/changelog_2.0.0-3.0.0.txt
  core/coreobjects/include/coreobjects/property_object_class_builder.h
  core/coreobjects/include/coreobjects/property_object_class_builder_impl.h
  core/coreobjects/src/property_object_class_builder_impl.cpp
Labels: bug

#68 Speed-up base-interface detection
  core/coretypes/include/coretypes/arguments.h
  core/coretypes/include/coretypes/intfs.h
  core/coretypes/tests/test_actual_interfaces.cpp
Labels: enhancement

#66 CI - Make Win32 build available (fixed pack and deploy scripts)
  .github/workflows/deploy.yml
  .github/workflows/package.yml
Labels: enhancement, ci

#49 [TBBAS-1148][TBBAS-1151] Typed TailReader and BlockReader, Time wrappers for readers
  bindings/python/core_types/include/py_core_types/py_converter.h
  bindings/python/opendaq/CMakeLists.txt
  bindings/python/opendaq/generated/reader/py_block_reader.cpp
  bindings/python/opendaq/generated/reader/py_stream_reader.cpp
  bindings/python/opendaq/generated/reader/py_tail_reader.cpp
  bindings/python/opendaq/generated/reader/py_time_reader.cpp
  bindings/python/opendaq/generated/signal/py_mock_signal.cpp
  bindings/python/opendaq/include/py_opendaq/py_mock_signal.h
  bindings/python/opendaq/include/py_opendaq/py_opendaq.h
  bindings/python/opendaq/include/py_opendaq/py_reader_traits.h
  bindings/python/opendaq/include/py_opendaq/py_typed_reader.h
  bindings/python/opendaq/py_opendaq.cpp
  bindings/python/tests/test_reader_datetime.py
  docs/Antora/modules/getting_started/pages/quick_start_application.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_last_n_samples.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timeouts.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timestamps.adoc
  examples/python/csv_writer.py
  examples/python/guide/read_signal.py
Labels: documentation, bindings:python

#72 Add core event triggers for Property Object
  changelog/changelog_2.0.0-3.0.0.txt
  core/coreobjects/include/coreobjects/core_event_args.h
  core/coreobjects/include/coreobjects/core_event_args_factory.h
  core/coreobjects/include/coreobjects/core_event_args_ids.h
  core/coreobjects/include/coreobjects/core_event_args_impl.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/src/CMakeLists.txt
  core/coreobjects/src/core_event_args_impl.cpp
  core/coretypes/include/coretypes/event_args_impl.h
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/tests/CMakeLists.txt
  core/opendaq/component/tests/test_component.cpp
  core/opendaq/component/tests/test_core_event.cpp
  core/opendaq/context/include/opendaq/context.h
  core/opendaq/context/include/opendaq/context_ptr.fwd_declare.h
  core/opendaq/context/src/CMakeLists.txt
  core/opendaq/modulemanager/include/opendaq/context_impl.h
  core/opendaq/modulemanager/src/context_impl.cpp
  core/opendaq/opendaq/mocks/include/opendaq/gmock/context.h
Labels: enhancement

#67 Feature/OPC-UA Vendor Supports
  external/CMakeLists.txt
  external/opcua_daq_types/CMakeLists.txt
  external/opcua_daq_types/daq_opcua_nodesets.h.in
  external/opcua_daq_types/hbk/CMakeLists.txt
  external/opcua_tms_types/CMakeLists.txt
  shared/libraries/opcua/opcuaserver/src/CMakeLists.txt
  shared/libraries/opcua/opcuaserver/src/opcuatmstypes.cpp
  shared/libraries/opcua/opcuaserver/tests/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms/include/opcuatms/converter_maps.h
  shared/libraries/opcuatms/opcuatms/include/opcuatms/opcuatms.h
  shared/libraries/opcuatms/opcuatms/include/opcuatms/type_mappings.h
  shared/libraries/opcuatms/opcuatms/src/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms/src/converters/argument_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/data_descriptor_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/data_rule_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/dict_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/dimension_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/dimension_rule_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/function_block_type_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/ratio_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/scaling_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/unit_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/core_types_utils.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_folder_factory.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_folder_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_function_block_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_input_port_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_io_folder_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_signal_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/tms_client.cpp
  shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/objects/tms_server_component.h
  shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/objects/tms_server_object.h
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_channel.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_device.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_eval_value.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_folder.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_function_block.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_input_port.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_object.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property_object.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_signal.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_helpers.h
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_channel.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_device.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_function_block.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_input_port.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_server.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_signal.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_channel.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_function_block.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_input_port.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_signal.cpp
  shared/libraries/opcuatms/tests/test_utils/CMakeLists.txt
  shared/libraries/opcuatms/tests/test_utils/tms_object_test.cpp
Labels: enhancement

#73 Fix open62541 CMake configure under aarch64 cross-compiler
  external/open62541/CMakeLists.txt
Labels: enhancement
