Repository openDAQ/openDAQ, pull requests merged in 2024-03, with the labels that each got.

#177 Add SDK version to device info
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/include/opendaq/device_info.h
  core/opendaq/device/include/opendaq/device_info_config.h
  core/opendaq/device/include/opendaq/device_info_factory.h
  core/opendaq/device/include/opendaq/device_info_impl.h
  core/opendaq/device/src/device_info_impl.cpp
  core/opendaq/device/tests/test_device_info.cpp
  modules/opcua_server_module/src/opcua_server_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  shared/libraries/config_protocol/tests/test_utils.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
  shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/tms_server.h
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_device.cpp
  shared/libraries/opcuatms/opcuatms_server/src/tms_server.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
Labels: enhancement

#180 .NET Bindings - NuGet package name already contains SHA for AWS
  .github/workflows/deploy.yml
Labels: bug, ci, bindings:c#

#189 Fix statistics vs2017 build
  modules/ref_fb_module/tests/test_fb_statistics.cpp
Labels: bug

#190 hiding not public signals in streaming lt
  shared/libraries/websocket_streaming/src/async_packet_reader.cpp
Labels: bug

#173 [TBBAS-1381] .NET Bindings - Provide minimal tests for CI
  .github/workflows/ci.yml
  bindings/dotnet/CMakeLists.txt
  bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/GlobalUsings.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/OpenDAQ_CITests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/openDAQ.Net.CI.Test.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesBaseObjectTests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesBoolTests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesFloatTests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesIntegerTests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesStringTests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDAQTestsBase.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDAQ_Tests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqHowToGuidesTests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqTranslatedCppTests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/openDAQ.Net.Test.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net.sln
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
  shared/tools/license-header-checker/ignore-filter.txt
Labels: enhancement, ci, bindings:c#

#186 getLastValue update
  core/opendaq/signal/include/opendaq/binary_data_packet_impl.h
  core/opendaq/signal/include/opendaq/data_packet.h
  core/opendaq/signal/include/opendaq/data_packet_impl.h
  core/opendaq/signal/include/opendaq/signal.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/signal/tests/test_binary_packet.cpp
  core/opendaq/signal/tests/test_signal.cpp
  shared/libraries/opcua/opcuashared/include/opcuashared/opcuaobject.h
  shared/libraries/opcuatms/opcuatms/include/opcuatms/converter_maps.h
  shared/libraries/opcuatms/opcuatms/src/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms/src/converters/complex_number_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/core_types_utils.cpp
  shared/libraries/opcuatms/opcuatms/tests/test_core_types_utils.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_signal.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_signal.cpp
Labels: enhancement, OPC UA

#188 ToDaqObject returns nullptr instead of throwing an exception.
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_impl.cpp
Labels: bug

#204 [TBBAS-1367] Make Enumeration and EnumerationType behave close to native Python enums
  bindings/python/core_types/generated/py_enumeration.cpp
  bindings/python/core_types/generated/py_enumeration_type.cpp
  bindings/python/core_types/generated/py_type_manager.cpp
  bindings/python/tests/test_core_types.py
Labels: bindings:python

#206 Add python gui example as openDAQ package's __main__ entrypoint
  bindings/python/package/METADATA.in
  bindings/python/package/build_pip.py
Labels: bindings:python

#213 Move ids parser to public
  core/opendaq/utility/src/CMakeLists.txt
Labels: bug

#117 Added support for EnumerationType properties in OPC UA
  core/coreobjects/include/coreobjects/property.h
  core/coreobjects/include/coreobjects/property_builder.h
  core/coreobjects/include/coreobjects/property_builder_impl.h
  core/coreobjects/include/coreobjects/property_factory.h
  core/coreobjects/include/coreobjects/property_impl.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/src/property_builder_impl.cpp
  core/coreobjects/src/property_impl.cpp
  core/coreobjects/tests/test_property.cpp
  core/coreobjects/tests/test_property_object.cpp
  core/coretypes/include/coretypes/coretype.h
  core/coretypes/include/coretypes/enumeration.h
  core/coretypes/include/coretypes/enumeration_factory.h
  core/coretypes/include/coretypes/enumeration_impl.h
  core/coretypes/src/enumeration_impl.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  shared/libraries/opcua/opcuaclient/include/opcuaclient/cached_reference_browser.h
  shared/libraries/opcua/opcuaserver/include/opcuaserver/opcuaaddnodeparams.h
  shared/libraries/opcua/opcuashared/include/opcuashared/opcuanodeid.h
  shared/libraries/opcua/opcuashared/include/opcuashared/opcuavariant.h
  shared/libraries/opcua/opcuashared/src/opcuanodeid.cpp
  shared/libraries/opcuatms/opcuatms/include/opcuatms/converter_maps.h
  shared/libraries/opcuatms/opcuatms/include/opcuatms/core_types_utils.h
  shared/libraries/opcuatms/opcuatms/src/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms/src/converters/base_object_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/generic_enumeration_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/generic_struct_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/core_types_utils.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/tms_client.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/tms_attribute_collector.cpp
  shared/libraries/opcuatms/opcuatms_client/src/tms_client.cpp
  shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/objects/tms_server_property.h
  shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/objects/tms_server_variable.h
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property_object.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_variable.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_property_object_advanced.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_fusion_device.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_property_object.cpp
Labels: enhancement

#215 Add config client setActive support
  shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_server_component.h
  shared/libraries/config_protocol/tests/test_config_client_server.cpp
  shared/libraries/config_protocol/tests/test_core_events.cpp
Labels: enhancement

#217 Allow convertible openDAQ structs over OPC UA
  core/coretypes/include/coretypes/type_manager_impl.h
  core/coretypes/src/struct_builder_impl.cpp
  core/coretypes/src/type_manager_impl.cpp
  core/coretypes/tests/test_type_manager.cpp
  shared/libraries/opcuatms/opcuatms/include/opcuatms/core_types_utils.h
  shared/libraries/opcuatms/opcuatms/src/converters/core_types_converter.cpp
  shared/libraries/opcuatms/opcuatms/src/core_types_utils.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_context.h
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/tms_client.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_context.cpp
  shared/libraries/opcuatms/opcuatms_client/src/tms_client.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property_object.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_property_object_advanced.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_fusion_device.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/tms_object_integration_test.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/tms_object_integration_test.h
Labels: bug, enhancement

#219 Fix compiling python bindings on Windows/MSVC in Debug configuration
  bindings/python/core_types/CMakeLists.txt
Labels: bug

#201 Support getLastValue for structs in core and fix bug in struct builder with tests
  core/coretypes/include/coretypes/struct_builder_ptr.h
  core/opendaq/reader/tests/test_stream_reader.cpp
  core/opendaq/signal/include/opendaq/binary_data_packet_impl.h
  core/opendaq/signal/include/opendaq/data_packet.h
  core/opendaq/signal/include/opendaq/data_packet_impl.h
  core/opendaq/signal/include/opendaq/signal.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/signal/src/data_descriptor_impl.cpp
  core/opendaq/signal/tests/test_data_descriptor.cpp
  core/opendaq/signal/tests/test_data_packet.cpp
  core/opendaq/signal/tests/test_signal.cpp
  docs/Antora/modules/background_info/pages/signals.adoc
  docs/tests/test_signals.cpp
Labels: bug, enhancement

#214 Make type manager thread safe
  core/coretypes/include/coretypes/type_manager_impl.h
  core/coretypes/src/type_manager_impl.cpp
  core/coretypes/tests/test_type_manager.cpp
  core/opendaq/logger/include/opendaq/logger_sink_last_message_private.h
  modules/native_streaming_client_module/src/native_streaming_device_impl.cpp
  modules/ref_fb_module/src/scaling_fb_impl.cpp
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/tests/test_utils.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/generic_struct_converter.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_property_object_advanced.cpp
Labels: enhancement

#223 [TBBAS-1299] Add support for multiple module paths in InstanceBuilder
  bindings/python/opendaq/generated/modulemanager/py_module_manager.cpp
  bindings/python/opendaq/generated/opendaq/py_instance_builder.cpp
  bindings/python/package/opendaq/__init__.py
  bindings/python/run_rtgen.sh
  changelog/changelog_2.0.0-3.0.0.txt
  core/opendaq/modulemanager/include/opendaq/module_manager.h
  core/opendaq/modulemanager/include/opendaq/module_manager_factory.h
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/opendaq/include/opendaq/instance_builder.h
  core/opendaq/opendaq/include/opendaq/instance_builder_impl.h
  core/opendaq/opendaq/src/instance_builder_impl.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
Labels: enhancement

#232 Support lists in getLastValue
  core/coretypes/include/coretypes/struct_type_factory.h
  core/opendaq/signal/include/opendaq/data_packet.h
  core/opendaq/signal/include/opendaq/data_packet_impl.h
  core/opendaq/signal/include/opendaq/signal.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/signal/src/data_descriptor_impl.cpp
  core/opendaq/signal/tests/test_signal.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_signal.cpp
Labels: enhancement
