Repository openDAQ/openDAQ, pull requests merged in 2024-12, with the labels that each got.

#626 [TBASS-1927] Property values are written before validation (release)
  bindings/python/core_objects/generated/py_property_value_event_args.cpp
  bindings/python/opendaq/generated/device/py_device_private.cpp
  bindings/python/opendaq/generated/signal/py_data_packet.cpp
  changelog/changelog_3.0.0-4.0.0.md
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/include/coreobjects/property_value_event_args.h
  core/coreobjects/include/coreobjects/property_value_event_args_factory.h
  core/coreobjects/include/coreobjects/property_value_event_args_impl.h
  core/coreobjects/src/property_value_event_args_impl.cpp
  docs/Antora-specs/antora.yml
  docs/Antora/antora.yml
  opendaq_version
  shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
  shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
Labels: bug

#631 Add "onAny" property value read and write events
  changelog/changelog_3.0.0-4.0.0.md
  core/coreobjects/include/coreobjects/property_object.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/tests/test_value_changed_events.cpp
  core/opendaq/opendaq/include/opendaq/instance_impl.h
  core/opendaq/opendaq/src/instance_impl.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_property_object_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
Labels: enhancement

#625 Component status extension
  changelog/changelog_3.0.0-4.0.0.md
  core/coreobjects/include/coreobjects/core_event_args.h
  core/coreobjects/include/coreobjects/core_event_args_impl.h
  core/coretypes/include/coretypes/enumeration.h
  core/coretypes/src/type_manager_impl.cpp
  core/opendaq/component/include/opendaq/component.h
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/include/opendaq/component_status_container.h
  core/opendaq/component/include/opendaq/component_status_container_impl.h
  core/opendaq/component/include/opendaq/component_status_container_private.h
  core/opendaq/component/tests/test_component.cpp
  core/opendaq/component/tests/test_component_status_container.cpp
  core/opendaq/functionblock/include/opendaq/function_block.h
  core/opendaq/modulemanager/src/context_impl.cpp
  docs/Antora/modules/knowledge_base/pages/components.adoc
  docs/tests/test_components.cpp
  modules/ref_fb_module/include/ref_fb_module/scaling_fb_impl.h
  modules/ref_fb_module/src/classifier_fb_impl.cpp
  modules/ref_fb_module/src/fft_fb_impl.cpp
  modules/ref_fb_module/src/power_fb_impl.cpp
  modules/ref_fb_module/src/power_reader_fb_impl.cpp
  modules/ref_fb_module/src/renderer_fb_impl.cpp
  modules/ref_fb_module/src/scaling_fb_impl.cpp
  modules/ref_fb_module/src/statistics_fb_impl.cpp
  modules/ref_fb_module/src/struct_decoder_fb_impl.cpp
  modules/ref_fb_module/src/trigger_fb_impl.cpp
  modules/ref_fb_module/tests/test_fb_statistics.cpp
  modules/ref_fb_module/tests/test_fb_trigger.cpp
  modules/ref_fb_module/tests/test_ref_fb_module.cpp
  modules/tests/test_ref_modules/test_ref_modules.cpp
Labels: enhancement

#636 Fix native reconnection issues
  docs/Antora-specs/antora.yml
  docs/Antora/antora.yml
  external/native_streaming/CMakeLists.txt
  opendaq_version
  shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
Labels: bug

#644 Fix status messages not propagated via native protocol
  core/opendaq/opendaq/tests/test_core_events.cpp
  modules/tests/test_opendaq_device_modules/CMakeLists.txt
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h
Labels: bug

#633 [TBBAS-1945] Python bindings: IEvent implementation
  bindings/python/core_objects/generated/py_property.cpp
  bindings/python/core_objects/generated/py_property_builder.cpp
  bindings/python/core_objects/generated/py_property_object.cpp
  bindings/python/core_types/CMakeLists.txt
  bindings/python/core_types/generated/py_event.cpp
  bindings/python/core_types/generated/py_event_handler.cpp
  bindings/python/core_types/include/py_core_types/py_core_types.h
  bindings/python/core_types/include/py_core_types/py_event_handler_impl.h
  bindings/python/core_types/src/py_core_types.cpp
  bindings/python/opendaq/generated/component/py_component.cpp
  bindings/python/opendaq/generated/context/py_context.cpp
  bindings/python/opendaq/generated/streaming/py_mirrored_signal_config.cpp
  bindings/python/run_rtgen.sh
  bindings/python/tests/test_property_system.py
  core/coretypes/include/coretypes/event_wrapper.h
  examples/python/component_event_handling.py
  shared/tools/RTGen/bin/RTGen.CSharp.dll
  shared/tools/RTGen/bin/RTGen.Cpp.dll
  shared/tools/RTGen/bin/RTGen.Delphi.dll
  shared/tools/RTGen/bin/RTGen.Library.dll
  shared/tools/RTGen/bin/RTGen.Python.dll
  shared/tools/RTGen/bin/rtgen.exe
  shared/tools/RTGen/src/project/RTGen.Python/Generators/PythonGenerator.cs
Labels: enhancement, bindings:python

#635 Remove root device on instance destruction
  core/opendaq/opendaq/include/opendaq/instance_impl.h
  core/opendaq/opendaq/src/instance_impl.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
Labels: enhancement

#651 [TBBAS-1992][TBBAS-1994] Support for python lists in multireader and how-to guides update
  bindings/python/opendaq/generated/reader/py_multi_reader.cpp
  bindings/python/tests/test_reader_datetime.py
  docs/Antora/modules/howto_guides/pages/howto_read_aligned_signals.adoc
Labels: documentation, enhancement, bindings:python

#634 [TBBAS-2018] Support adding and removing nested function blocks in Python GUI
  examples/python/gui_demo.py
  examples/python/gui_demo/components/add_function_block_dialog.py
  examples/python/gui_demo/utils.py
Labels: enhancement, bindings:python

#649 Upload Python Wheels to S3 even if not `refs/heads/main`
  .github/workflows/deploy.yml
Labels: ci

#637 Make attributes editable in Python GUI Demo Application
  examples/python/gui_demo/components/attributes_dialog.py
Labels: bug, bindings:python

#653 Fix local device discovery and serialization on id clashes
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/tests/test_device.cpp
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/opendaq/mocks/mock_device_module.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
Labels: bug
