Repository openDAQ/openDAQ, pull requests merged in 2024-09, with the labels that each got.

#407 Other/optimize begin end update config protocol
  modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
  modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_object.h
  shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_server.h
  shared/libraries/config_protocol/include/config_protocol/config_server_component.h
  shared/libraries/config_protocol/include/config_protocol/config_server_device.h
  shared/libraries/config_protocol/include/config_protocol/config_server_input_port.h
  shared/libraries/config_protocol/include/config_protocol/config_server_signal.h
  shared/libraries/config_protocol/src/config_protocol.cpp
  shared/libraries/config_protocol/src/config_protocol_client.cpp
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/config_protocol/tests/test_config_client_server.cpp
  shared/libraries/config_protocol/tests/test_config_packet.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_access_control.cpp
Labels: enhancement

#484 Make Python wheel install instructions explicit
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
Labels: documentation

#485 Fix issue with the server not releasing queued packets upon client di…
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
Labels: bug

#487 Fix issue with the server not releasing queued packets upon client di…
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
Labels: bug

#486 Fix issue with the server not releasing queued packets upon client di…
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
Labels: bug

#492 Check that streaming source is added to the signal before setting it as active
  core/opendaq/modulemanager/src/module_manager_impl.cpp
Labels: enhancement

#493 Check that streaming source is added to the signal before setting it as active
  core/opendaq/modulemanager/src/module_manager_impl.cpp
Labels: enhancement

#494 Check that streaming source is added to the signal before setting it as active
  core/opendaq/modulemanager/src/module_manager_impl.cpp
Labels: enhancement

#379 <TBBAS-1697> Fix native streaming data processing callbacks:
  modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
  modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_impl.h
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_device_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_impl.cpp
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
Labels: bug

#501 Backport making `server_impl.h` public and version bump
  bindings/dotnet/CMakeLists.txt
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
  core/CMakeLists.txt
  core/opendaq/server/src/CMakeLists.txt
  docs/Antora-specs/antora.yml
  docs/Antora/antora.yml
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_cpp.adoc
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
  examples/CMakeLists.txt
  examples/cpp/CMakeLists.txt
  modules/audio_device_module/CMakeLists.txt
  modules/empty_module/CMakeLists.txt
  modules/native_streaming_client_module/CMakeLists.txt
  modules/native_streaming_server_module/CMakeLists.txt
  modules/opcua_client_module/CMakeLists.txt
  modules/opcua_server_module/CMakeLists.txt
  modules/ref_device_module/CMakeLists.txt
  modules/ref_fb_module/CMakeLists.txt
  modules/websocket_streaming_client_module/CMakeLists.txt
  modules/websocket_streaming_server_module/CMakeLists.txt
  opendaq_version
  shared/libraries/opcuatms/opcuatms/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_client/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_server/CMakeLists.txt
Labels: bug

#500 Make `server_impl.h` public
  core/opendaq/server/src/CMakeLists.txt
Labels: bug

#508 Improve thread-safety of config protocol client
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/src/config_protocol_client.cpp
Labels: bug

#510 Fix issue with native device custom statuses
  modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
Labels: bug

#515 Proof read access control howto guide
  docs/Antora/modules/howto_guides/pages/howto_access_control.adoc
Labels: documentation

#519 Fix a minor typo in Antora docs
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
Labels: documentation
