Repository openDAQ/openDAQ, pull requests merged in 2024-11, with the labels that each got.

#573 Fix MSVC warning on casting results of parsing event packet
  core/opendaq/reader/src/signal_reader.cpp
Labels: bug

#572 <TBBAS-1892> Restore DeviceInfo fields after native device update
  modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
Labels: bug

#574 <TBBAS-1826> Add PrimaryAddressType field to prioritize IPv4/v6 connections in add device general config
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  modules/tests/test_opendaq_device_modules/test_default_config.cpp
  modules/tests/test_opendaq_device_modules/test_helpers/test_helpers.h
  modules/tests/test_opendaq_device_modules/test_streaming.cpp
Labels: enhancement

#560 <TBBAS-1845> mitigate out-of-memory risk on server-side for native streaming
  docs/tests/test_modules.cpp
  external/native_streaming/CMakeLists.txt
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
  modules/native_streaming_server_module/tests/test_native_streaming_server_module.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/server_session_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h
  shared/libraries/native_streaming_protocol/src/base_session_handler.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
  shared/libraries/native_streaming_protocol/src/server_session_handler.cpp
  shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
  shared/libraries/packet_streaming/include/packet_streaming/packet_streaming.h
  shared/libraries/packet_streaming/include/packet_streaming/packet_streaming_server.h
  shared/libraries/packet_streaming/src/packet_streaming.cpp
  shared/libraries/packet_streaming/src/packet_streaming_server.cpp
  shared/libraries/packet_streaming/tests/packet_transmission.cpp
  shared/libraries/packet_streaming/tests/test_packet_streaming.cpp
Labels: bug

#565 [TBBAS-1874] Allow readers creation with already-connected input ports
  changelog/changelog_3.0.0-4.0.0.md
  core/opendaq/reader/include/opendaq/multi_reader_impl.h
  core/opendaq/reader/include/opendaq/reader_impl.h
  core/opendaq/reader/include/opendaq/stream_reader_impl.h
  core/opendaq/reader/src/block_reader_impl.cpp
  core/opendaq/reader/src/multi_reader_impl.cpp
  core/opendaq/reader/src/packet_reader_impl.cpp
  core/opendaq/reader/src/signal_reader.cpp
  core/opendaq/reader/src/stream_reader_impl.cpp
  core/opendaq/reader/src/tail_reader_impl.cpp
  core/opendaq/reader/tests/test_block_reader.cpp
  core/opendaq/reader/tests/test_multi_reader.cpp
  core/opendaq/reader/tests/test_stream_reader.cpp
  core/opendaq/reader/tests/test_tail_reader.cpp
  core/opendaq/signal/include/opendaq/connection_impl.h
  core/opendaq/signal/include/opendaq/connection_internal.h
  core/opendaq/signal/include/opendaq/input_port_impl.h
  core/opendaq/signal/src/CMakeLists.txt
  core/opendaq/signal/src/connection_impl.cpp
  modules/ref_fb_module/tests/test_ref_fb_module.cpp
Labels: enhancement

#579 Consolidate protocol specs and user guide into a single documentation site
  .github/workflows/deploy.yml
  antora-playbook-dev.yml
  antora-playbook.yml
  antora-specs-playbook-dev.yml
  antora-specs-playbook.yml
  docs/Antora-specs/antora.yml
Labels: documentation, ci

#577 Bump version to `3.10.0` and add `opendaq_version_bump.py` script
  .github/workflows/build_antora_docs.yml
  .github/workflows/deploy.yml
  docs/Antora-specs/antora.yml
  docs/Antora/antora.yml
  opendaq_version
  opendaq_version_bump.py
Labels: enhancement

#575 [TBBAS-1889] Failed to call getAvailableDevices client native device
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_client_sync_component_impl.h
  shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
Labels: bug

#540 Other/property object sync
  changelog/changelog_3.0.0-4.0.0.md
  core/coreobjects/include/coreobjects/coercer.h
  core/coreobjects/include/coreobjects/coercer_impl.h
  core/coreobjects/include/coreobjects/eval_nodes.h
  core/coreobjects/include/coreobjects/eval_value.h
  core/coreobjects/include/coreobjects/eval_value_impl.h
  core/coreobjects/include/coreobjects/property_impl.h
  core/coreobjects/include/coreobjects/property_internal.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/include/coreobjects/property_object_internal.h
  core/coreobjects/include/coreobjects/validator.h
  core/coreobjects/include/coreobjects/validator_impl.h
  core/coreobjects/src/coercer_impl.cpp
  core/coreobjects/src/eval_nodes.cpp
  core/coreobjects/src/eval_value_impl.cpp
  core/coreobjects/src/validator_impl.cpp
  core/coreobjects/tests/test_property_object.cpp
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/include/opendaq/component_status_container_impl.h
  core/opendaq/component/include/opendaq/folder_impl.h
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/functionblock/include/opendaq/function_block_wrapper_impl.h
  core/opendaq/functionblock/src/function_block_wrapper_impl.cpp
  core/opendaq/opendaq/mocks/mock_fb_dynamic_input_ports.cpp
  core/opendaq/opendaq/mocks/mock_fb_dynamic_output_ports.cpp
  core/opendaq/reader/include/opendaq/multi_reader_builder.h
  core/opendaq/signal/include/opendaq/connection.h
  core/opendaq/signal/include/opendaq/input_port_impl.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/streaming/include/opendaq/mirrored_device_impl.h
  core/opendaq/streaming/include/opendaq/mirrored_signal_impl.h
  core/opendaq/synchronization/include/opendaq/sync_component.h
  modules/audio_device_module/include/audio_device_module/wav_writer_fb_impl.h
  modules/audio_device_module/src/audio_channel_impl.cpp
  modules/audio_device_module/src/audio_device_impl.cpp
  modules/audio_device_module/src/wav_writer_fb_impl.cpp
  modules/ref_device_module/src/ref_can_channel_impl.cpp
  modules/ref_device_module/src/ref_channel_impl.cpp
  modules/ref_device_module/src/ref_device_impl.cpp
  modules/ref_fb_module/src/classifier_fb_impl.cpp
  modules/ref_fb_module/src/fft_fb_impl.cpp
  modules/ref_fb_module/src/power_fb_impl.cpp
  modules/ref_fb_module/src/power_reader_fb_impl.cpp
  modules/ref_fb_module/src/renderer_fb_impl.cpp
  modules/ref_fb_module/src/scaling_fb_impl.cpp
  modules/ref_fb_module/src/statistics_fb_impl.cpp
  modules/ref_fb_module/src/struct_decoder_fb_impl.cpp
  modules/ref_fb_module/src/trigger_fb_impl.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_input_port_impl.h
Labels: enhancement, integration breaking

#585 [Bug:] Fix update client property value while setting new value inside callback
  core/coreobjects/include/coreobjects/property_object_impl.h
  shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
Labels: bug

#584 Run flaky tests on nightly basis reusing existing CI jobs
  .github/workflows/ci.yml
  .github/workflows/unstable_tests.yml
  CMakeBasePresets.json
  CMakeLists.txt
  core/opendaq/reader/tests/test_multi_reader.cpp
  docs/tests/test_quick_start.cpp
  modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
  modules/tests/test_opendaq_device_modules/test_streaming.cpp
  modules/tests/test_opendaq_device_modules/test_subdevices.cpp
  modules/tests/test_ref_modules/test_ref_modules.cpp
  shared/libraries/config_protocol/tests/test_c2d_streaming.cpp
  shared/libraries/testutils/include/testutils/testutils.h
  shared/libraries/testutils/src/base_test_listener.cpp
Labels: ci

#581 [TBBAS-1819] Python GUI: Property metadata view
  examples/python/gui_demo.py
  examples/python/gui_demo/app_context.py
  examples/python/gui_demo/components/add_config_dialog.py
  examples/python/gui_demo/components/add_device_dialog.py
  examples/python/gui_demo/components/attributes_dialog.py
  examples/python/gui_demo/components/dialog.py
  examples/python/gui_demo/components/edit_container_property.py
  examples/python/gui_demo/components/load_instance_config_dialog.py
  examples/python/gui_demo/components/metadata_dialog.py
  examples/python/gui_demo/components/metadata_fields_selector_dialog.py
  examples/python/gui_demo/components/properties_view.py
  examples/python/gui_demo/utils.py
Labels: enhancement, bindings:python

#587 Automatically populate default config in module implementation
  core/coreobjects/include/coreobjects/component_type_impl.h
  core/opendaq/modulemanager/include/opendaq/module_impl.h
  core/opendaq/opendaq/tests/CMakeLists.txt
  core/opendaq/opendaq/tests/test_module_callbacks.cpp
  core/opendaq/server/tests/test_server_type.cpp
  docs/tests/test_examples.cpp
  docs/tests/test_quick_start.cpp
  modules/ref_device_module/src/ref_device_impl.cpp
  modules/ref_device_module/src/ref_device_module_impl.cpp
  modules/ref_device_module/tests/test_ref_device_module.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
Labels: enhancement

#592 [TBBAS-1810] .NET Bindings - Prepare NuGet package (create release NuGet package in package.yml)
  .github/workflows/package.yml
  .github/workflows/reusable_nuget_creation_and_test.yml
  bindings/dotnet/openDAQ.Net/README.md
  bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/OpenDAQ_CITests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/media/README.md
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
Labels: ci, bindings:c#

#583 Component update context improvement
  changelog/changelog_3.0.0-4.0.0.md
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/include/opendaq/component_update_context_impl.h
  core/opendaq/component/src/update_parameters_impl.cpp
  core/opendaq/functionblock/tests/test_fb_wrapper.cpp
  core/opendaq/opendaq/mocks/include/opendaq/gmock/signal.h
  core/opendaq/opendaq/src/instance_impl.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
  core/opendaq/signal/include/opendaq/input_port_impl.h
  core/opendaq/signal/include/opendaq/signal_container_impl.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/signal/include/opendaq/signal_private.h
  core/opendaq/signal/tests/test_input_port.cpp
  core/opendaq/streaming/include/opendaq/mirrored_signal_impl.h
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_mirrored_ext_sig_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_server_component.h
  shared/libraries/config_protocol/src/config_mirrored_ext_sig_impl.cpp
Labels: bug

#601 .NET Bindings - Fixed NuGet package creation in CI
  .github/workflows/package.yml
  .github/workflows/reusable_nuget_creation_and_test.yml
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
Labels: bug, ci, bindings:c#

#612 Other/make breaking change obvious
  core/coreobjects/include/coreobjects/core_event_args_factory.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/functionblock/include/opendaq/function_block_impl.h
  core/opendaq/signal/include/opendaq/signal_container_impl.h
  core/opendaq/signal/src/data_rule_impl.cpp
  modules/ref_device_module/src/ref_device_impl.cpp
  modules/ref_fb_module/src/renderer_fb_impl.cpp
  modules/ref_fb_module/src/statistics_fb_impl.cpp
Labels: enhancement, integration breaking

#615 Serialize the Active flag for all Components
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/device/tests/test_device.cpp
  core/opendaq/signal/include/opendaq/signal_impl.h
Labels: bug

#617 Python bindings Wheels 3.13
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/package.yml
  bindings/python/package/METADATA.in
  bindings/python/package/build_pip.py
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
Labels: enhancement, ci, bindings:python
