Repository openDAQ/openDAQ, pull requests merged in 2024-08, with the labels that each got.

#416 Fixing flaky multireader test in ci
  core/opendaq/reader/tests/test_multi_reader.cpp
Labels: bug, ci

#433 Fix "NativeDeviceModulesTest.MultiClientReadChangingSignal" test
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
  modules/tests/test_opendaq_device_modules/test_subdevices.cpp
  modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
Labels: ci

#435 Replace remaining `Blueberry d.o.o.` occurrences with `openDAQ d.o.o.`
  bindings/dotnet/openDAQ.Net/README.md
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
  bindings/python/package/METADATA.in
  cmake/Packing.cmake
  cmake/version/version.rc.in
  shared/tools/RTGen/src/project/RTGen.CSharp/Properties/AssemblyInfo.cs
  shared/tools/RTGen/src/project/RTGen.Cpp/Properties/AssemblyInfo.cs
  shared/tools/RTGen/src/project/RTGen.Delphi/Properties/AssemblyInfo.cs
  shared/tools/RTGen/src/project/RTGen.Library/Properties/AssemblyInfo.cs
  shared/tools/RTGen/src/project/RTGen.Python/Properties/AssemblyInfo.cs
  shared/tools/RTGen/src/project/RTGen/Properties/AssemblyInfo.cs
Labels: bug, documentation

#438 Fix multi threaded Config protocol RPC
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/src/config_protocol_client.cpp
Labels: bug

#437 Bump version of `seanmiddleditch/gha-setup-ninja`
  .github/workflows/ci.yml
Labels: ci

#442 Add IProperty get/setValue
  bindings/python/core_objects/generated/py_property.cpp
  changelog/changelog_3.0.0-4.0.0.txt
  core/coreobjects/include/coreobjects/eval_value_helpers.h
  core/coreobjects/include/coreobjects/eval_value_impl.h
  core/coreobjects/include/coreobjects/property.h
  core/coreobjects/include/coreobjects/property_impl.h
  core/coreobjects/src/eval_value_impl.cpp
  core/coreobjects/tests/amplifier_test.cpp
  core/opendaq/functionblock/include/opendaq/property_wrapper_impl.h
  core/opendaq/functionblock/src/property_wrapper_impl.cpp
  core/opendaq/reader/include/opendaq/reader_status.h
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_amplifier.cpp
Labels: enhancement

#448 Fix opcua warnings
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
Labels: bug

#447 Update onPropertyRead/Write calling logic on owned properties
  changelog/changelog_3.0.0-4.0.0.txt
  core/coreobjects/include/coreobjects/property_impl.h
  core/coreobjects/include/coreobjects/property_internal.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/tests/test_value_changed_events.cpp
  core/coretypes/include/coretypes/event.h
  core/coretypes/include/coretypes/event_impl.h
  core/coretypes/include/coretypes/event_ptr.h
  core/coretypes/include/coretypes/event_wrapper.h
  core/coretypes/src/event_impl.cpp
Labels: bug, enhancement

#458 Properly install opendaq version generated header
  core/opendaq/CMakeLists.txt
  core/opendaq/opendaq/src/CMakeLists.txt
Labels: bug

#459 Properly install opendaq version generated header (release 3.2)
  core/opendaq/CMakeLists.txt
  core/opendaq/opendaq/src/CMakeLists.txt
Labels: bug

#460 Bugfix/buildable with yocto
  cmake/openDAQConfig.cmake.in
  external/open62541/CMakeLists.txt
Labels: bug

#464 Fix Python GUI Demo app gear icon click action
  examples/python/gui_demo.py
  examples/python/gui_demo/components/attributes_dialog.py
  examples/python/gui_demo/components/properties_view.py
Labels: bug

#461 Fix: Build dependencies via find_package()
  cmake/openDAQConfig.cmake.in
  external/open62541/CMakeLists.txt
Labels: bug
