Repository openDAQ/openDAQ, pull requests merged in 2024-01, with the labels that each got.

#78 Add core structure changed events
  core/coreobjects/include/coreobjects/core_event_args.h
  core/coreobjects/include/coreobjects/core_event_args_factory.h
  core/coreobjects/include/coreobjects/core_event_args_ids.h
  core/coreobjects/include/coreobjects/core_event_args_impl.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/include/coreobjects/property_object_internal.h
  core/coreobjects/src/CMakeLists.txt
  core/coreobjects/src/core_event_args_impl.cpp
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/include/opendaq/folder_impl.h
  core/opendaq/component/src/CMakeLists.txt
  core/opendaq/component/tests/CMakeLists.txt
  core/opendaq/component/tests/test_core_event.cpp
  core/opendaq/device/include/opendaq/core_opendaq_event_args.h
  core/opendaq/device/include/opendaq/core_opendaq_event_args_factory.h
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/src/CMakeLists.txt
  core/opendaq/device/src/core_opendaq_event_args_impl.cpp
  core/opendaq/functionblock/include/opendaq/function_block_impl.h
  core/opendaq/opendaq/include/opendaq/opendaq.h
  core/opendaq/opendaq/mocks/include/opendaq/mock/mock_device_module.h
  core/opendaq/opendaq/mocks/mock_device_module.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
  core/opendaq/opendaq/tests/CMakeLists.txt
  core/opendaq/opendaq/tests/test_core_events.cpp
  core/opendaq/signal/include/opendaq/signal_container_impl.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/signal/src/input_port_impl.cpp
Labels: enhancement

#92 Add "/" prefix to global IDs
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/tests/test_component.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
  core/opendaq/signal/tests/test_signal_container.cpp
  modules/ref_device_module/tests/test_ref_device_module.cpp
  modules/tests/test_opendaq_device_modules/test_device_modules.cpp
Labels: enhancement

#94 Skip writing Property object values if they do not constitute a value change
  core/coreobjects/include/coreobjects/property_object.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/tests/test_property_object.cpp
  core/opendaq/opendaq/tests/test_core_events.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_property_object.cpp
Labels: enhancement

#91 Fix Readers detection of Signal's raw sample-type
  core/opendaq/reader/include/opendaq/reader_impl.h
  core/opendaq/reader/include/opendaq/typed_reader.h
  core/opendaq/reader/src/signal_reader.cpp
  core/opendaq/reader/src/stream_reader_impl.cpp
  core/opendaq/reader/src/typed_reader.cpp
Labels: bug

#101 Update the minimum required CMake version to avoid deprecation warnings
  core/coreobjects/CMakeLists.txt
  core/coretypes/CMakeLists.txt
  core/opendaq/component/CMakeLists.txt
  core/opendaq/context/CMakeLists.txt
  core/opendaq/device/CMakeLists.txt
  core/opendaq/functionblock/CMakeLists.txt
  core/opendaq/logger/CMakeLists.txt
  core/opendaq/modulemanager/CMakeLists.txt
  core/opendaq/opendaq/CMakeLists.txt
  core/opendaq/reader/CMakeLists.txt
  core/opendaq/scheduler/CMakeLists.txt
  core/opendaq/server/CMakeLists.txt
  core/opendaq/signal/CMakeLists.txt
  core/opendaq/streaming/CMakeLists.txt
  core/opendaq/utility/CMakeLists.txt
  modules/audio_device_module/CMakeLists.txt
  modules/empty_module/CMakeLists.txt
  modules/native_streaming_client_module/CMakeLists.txt
  modules/native_streaming_server_module/CMakeLists.txt
  modules/opcua_client_module/CMakeLists.txt
  modules/opcua_server_module/CMakeLists.txt
  modules/ref_device_module/CMakeLists.txt
  modules/websocket_streaming_client_module/CMakeLists.txt
  modules/websocket_streaming_server_module/CMakeLists.txt
  shared/libraries/discovery/CMakeLists.txt
  shared/libraries/native_streaming_protocol/CMakeLists.txt
  shared/libraries/opcua/opcuaclient/CMakeLists.txt
  shared/libraries/opcua/opcuaserver/CMakeLists.txt
  shared/libraries/opcua/opcuashared/CMakeLists.txt
  shared/libraries/opcua/tests/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_client/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_server/CMakeLists.txt
  shared/libraries/opcuatms/tests/CMakeLists.txt
  shared/libraries/packet_streaming/CMakeLists.txt
  shared/libraries/testutils/CMakeLists.txt
  shared/libraries/utils/CMakeLists.txt
  shared/libraries/websocket_streaming/CMakeLists.txt
  simulator/simulator_app/CMakeLists.txt
Labels: enhancement

#93 Freeze and clone nested object-type property default values
  bindings/python/opendaq/generated/component/py_component.cpp
  bindings/python/opendaq/generated/component/py_component_private.cpp
  bindings/python/opendaq/generated/component/py_search_filter.cpp
  bindings/python/opendaq/generated/context/py_context.cpp
  bindings/python/tests/test_property_system.py
  changelog/changelog_2.0.0-3.0.0.txt
  core/coreobjects/include/coreobjects/core_event_args.h
  core/coreobjects/include/coreobjects/core_event_args_factory.h
  core/coreobjects/include/coreobjects/property.h
  core/coreobjects/include/coreobjects/property_builder_impl.h
  core/coreobjects/include/coreobjects/property_impl.h
  core/coreobjects/include/coreobjects/property_object.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/include/coreobjects/property_object_internal.h
  core/coreobjects/src/core_event_args_impl.cpp
  core/coreobjects/tests/test_property_object.cpp
  core/opendaq/component/include/opendaq/component_private.h
  core/opendaq/functionblock/tests/test_fb_wrapper.cpp
  core/opendaq/opendaq/src/CMakeLists.txt
  core/opendaq/opendaq/tests/test_core_events.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
  docs/Antora/modules/background_info/pages/property_system.adoc
  docs/tests/test_property_system.cpp
  modules/ref_device_module/src/CMakeLists.txt
  shared/libraries/opcuatms/tests/opcuatms_integration/test_property_object_advanced.cpp
Labels: bug, enhancement

#97 Tags rework
  bindings/python/opendaq/CMakeLists.txt
  bindings/python/opendaq/generated/component/py_tags.cpp
  bindings/python/opendaq/generated/component/py_tags_private.cpp
  bindings/python/opendaq/include/py_opendaq/py_opendaq.h
  bindings/python/opendaq/py_opendaq.cpp
  bindings/python/run_rtgen.sh
  changelog/changelog_2.0.0-3.0.0.txt
  core/coreobjects/include/coreobjects/core_event_args.h
  core/coreobjects/include/coreobjects/core_event_args_ids.h
  core/coreobjects/include/coreobjects/core_event_args_impl.h
  core/opendaq/component/include/opendaq/component.h
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/include/opendaq/tags.h
  core/opendaq/component/include/opendaq/tags_factory.h
  core/opendaq/component/include/opendaq/tags_impl.h
  core/opendaq/component/include/opendaq/tags_private.h
  core/opendaq/component/src/CMakeLists.txt
  core/opendaq/component/src/search_filter_impl.cpp
  core/opendaq/component/src/tags_impl.cpp
  core/opendaq/component/tests/CMakeLists.txt
  core/opendaq/component/tests/test_component.cpp
  core/opendaq/component/tests/test_folder.cpp
  core/opendaq/component/tests/test_tags.cpp
  core/opendaq/device/include/opendaq/core_opendaq_event_args.h
  core/opendaq/device/include/opendaq/core_opendaq_event_args_factory.h
  core/opendaq/device/src/core_opendaq_event_args_impl.cpp
  core/opendaq/functionblock/tests/test_channel.cpp
  core/opendaq/functionblock/tests/test_function_block.cpp
  core/opendaq/opendaq/include/opendaq/instance_impl.h
  core/opendaq/opendaq/include/opendaq/opendaq.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/component.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/signal.h
  core/opendaq/opendaq/src/instance_impl.cpp
  core/opendaq/opendaq/tests/test_core_events.cpp
  core/opendaq/utility/include/opendaq/tags_impl.h
  core/opendaq/utility/src/CMakeLists.txt
  core/opendaq/utility/src/tags_impl.cpp
  core/opendaq/utility/tests/CMakeLists.txt
  shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h
  shared/libraries/config_protocol/tests/test_config_serialization.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_tags_factory.h
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_tags_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_component_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_tags_impl.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_input_port.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_component.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_folder.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_input_port.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_signal.cpp
Labels: enhancement

#106 Fixed deployment cleanup filter for AWS
  .github/workflows/deploy.yml
Labels: bug, ci

#119 install missing public core headers
  core/opendaq/component/src/CMakeLists.txt
Labels: bug

#114 Bugfix: Float Type not supported in Structures
  shared/libraries/opcua/opcuashared/include/opcuashared/opcuavariant.h
  shared/libraries/opcua/opcuashared/src/opcuavariant.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/core_types_converter.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_fusion_device.cpp
Labels: bug
