Repository openDAQ/openDAQ, pull requests merged in 2024-02, with the labels that each got.

#103 [TBBAS-939] Error recovery and logging in OPC UA client. Add debug logger sink
  changelog/changelog_2.0.0-3.0.0.txt
  core/opendaq/logger/include/opendaq/logger_sink.h
  core/opendaq/logger/include/opendaq/logger_sink_base_private.h
  core/opendaq/logger/include/opendaq/logger_sink_factory.h
  core/opendaq/logger/include/opendaq/logger_sink_impl.h
  core/opendaq/logger/include/opendaq/logger_sink_last_message_impl.h
  core/opendaq/logger/include/opendaq/logger_sink_last_message_private.h
  core/opendaq/logger/src/CMakeLists.txt
  core/opendaq/logger/src/logger_component_impl.cpp
  core/opendaq/logger/src/logger_impl.cpp
  core/opendaq/logger/src/logger_sink_impl.cpp
  modules/tests/test_opendaq_device_modules/test_device_modules.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_component_impl.h
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_folder_impl.h
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_function_block_impl.h
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_io_folder_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_component_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_folder_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_function_block_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_function_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_input_port_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_io_folder_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_procedure_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_signal_impl.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_property_object_advanced.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_amplifier.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_function_property.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_property_object.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/tms_object_integration_test.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/tms_object_integration_test.h
  shared/tools/RTGen/src/project/RTGen/Examples/async_channel_buffer.h
Labels: enhancement

#124 fix OPENDAQ_ENABLE_NATIVE_STREAMING: always create RTGen output dir if it doesn't exist
  cmake/RTGen.cmake
Labels: bug

#130 Add getIsSynchronized method to multi reader
  core/opendaq/reader/include/opendaq/multi_reader.h
  core/opendaq/reader/include/opendaq/multi_reader_impl.h
  core/opendaq/reader/src/multi_reader_impl.cpp
  core/opendaq/reader/tests/test_multi_reader.cpp
Labels: enhancement

#131 Add missing include for std::tolower
  core/opendaq/opendaq/src/json_config_provider_impl.cpp
Labels: bug

#132 Support changing OPENDAQ_MODULE_SUFFIX
  CMakeLists.txt
Labels: enhancement

#135 Include hidden input ports on update
  core/opendaq/functionblock/include/opendaq/function_block_impl.h
Labels: bug

#128 Update open62541 to opendaq-4 version
  external/open62541/CMakeLists.txt
Labels: bug

#134 Add option to multi reader to start reading on the full unit of the domain
  core/opendaq/reader/include/opendaq/multi_reader.h
  core/opendaq/reader/include/opendaq/multi_reader_impl.h
  core/opendaq/reader/include/opendaq/multi_typed_reader.h
  core/opendaq/reader/include/opendaq/reader_factory.h
  core/opendaq/reader/src/multi_reader_impl.cpp
  core/opendaq/reader/tests/test_multi_reader.cpp
Labels: enhancement

#141 Apply properties on update end in order
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/tests/amplifier_test.cpp
Labels: bug

#142 Test trigger using SameThread and minor trigger function block changes
  modules/ref_fb_module/include/ref_fb_module/trigger_fb_impl.h
  modules/ref_fb_module/src/ref_fb_module_impl.cpp
  modules/ref_fb_module/src/trigger_fb_impl.cpp
  modules/ref_fb_module/tests/test_fb_trigger.cpp
Labels: bug

#136 Allow adding function blocks on non-default root devices
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/include/opendaq/device_private.h
  core/opendaq/opendaq/include/opendaq/client_impl.h
  core/opendaq/opendaq/include/opendaq/client_private.h
  core/opendaq/opendaq/include/opendaq/instance_impl.h
  core/opendaq/opendaq/src/CMakeLists.txt
  core/opendaq/opendaq/src/client_impl.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
Labels: bug, enhancement

#138 A few minor stylistic changes to trigger function block
  modules/ref_fb_module/include/ref_fb_module/trigger_fb_impl.h
  modules/ref_fb_module/src/trigger_fb_impl.cpp
  modules/ref_fb_module/tests/test_fb_trigger.cpp
Labels: enhancement

#148 Inline static destructors are called multiple times (VS 2017 compiler bug) (Part 2)
  core/opendaq/signal/include/opendaq/signal_impl.h
Labels: bug

#149 Fix first call of TmsClientDevice::GetTickSinceOrigin
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_device_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
Labels: bug

#145 add howto on simple measure of single value
  docs/Antora/modules/howto_guides/nav-howto-guides.adoc
  docs/Antora/modules/howto_guides/pages/howto_measure_single_value.adoc
Labels: documentation

#152 Added .NET Bindings generation flag to cmake preset "package"
  CMakePresets.json
Labels: bug, ci, bindings:c#

#151 RTGen - Implemented templateType attribute usage for factory functions
  core/opendaq/context/include/opendaq/context.h
  core/opendaq/logger/include/opendaq/logger.h
  core/opendaq/reader/include/opendaq/multi_reader.h
  shared/tools/RTGen/bin/RTGen.CSharp.dll
  shared/tools/RTGen/bin/RTGen.Cpp.dll
  shared/tools/RTGen/bin/RTGen.Delphi.dll
  shared/tools/RTGen/bin/RTGen.Library.dll
  shared/tools/RTGen/bin/RTGen.Python.dll
  shared/tools/RTGen/bin/rtgen.exe
  shared/tools/RTGen/src/project/RTGen.CSharp/Generators/CSharpGenerator.cs
  shared/tools/RTGen/src/project/RTGen.Cpp/Parser/RTGenListener.cs
Labels: enhancement, bindings:python, bindings:c#, bindings:delphi

#140 [TBBAS-1162] Python GUI App refactoring
  examples/python/gui_demo.py
Labels: enhancement

#146 implement logic for signal.setPublic(...)
  core/opendaq/opendaq/mocks/mock_fb.cpp
  core/opendaq/opendaq/mocks/mock_physical_device.cpp
  core/opendaq/signal/include/opendaq/signal_container_impl.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/streaming/include/opendaq/streaming_impl.h
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
  shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_device.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_function_block.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_function_block.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_integration.cpp
  shared/libraries/websocket_streaming/src/streaming_server.cpp
Labels: bug, enhancement

#162 [TBBAS-1057] RTGen fix in CSharpGenerator for correct out argument handling in Readers
  shared/tools/RTGen/bin/RTGen.CSharp.dll
  shared/tools/RTGen/bin/RTGen.Cpp.dll
  shared/tools/RTGen/bin/RTGen.Delphi.dll
  shared/tools/RTGen/bin/RTGen.Library.dll
  shared/tools/RTGen/bin/RTGen.Python.dll
  shared/tools/RTGen/bin/Templates/csharp.method.impl.ret.template
  shared/tools/RTGen/bin/Templates/csharp.method.impl.samplereader.template
  shared/tools/RTGen/bin/rtgen.exe
  shared/tools/RTGen/src/project/RTGen.CSharp/Generators/CSharpGenerator.cs
  shared/tools/RTGen/src/project/RTGen.CSharp/Templates/csharp.method.impl.ret.template
  shared/tools/RTGen/src/project/RTGen.CSharp/Templates/csharp.method.impl.samplereader.template
Labels: bug, ci, bindings:c#

#153 Fixing simulator config path
  core/opendaq/opendaq/include/opendaq/path_tool.h
  core/opendaq/opendaq/src/CMakeLists.txt
  core/opendaq/opendaq/src/json_config_provider_impl.cpp
  core/opendaq/opendaq/src/path_tool.cpp
  simulator/Vagrantfile
  simulator/simulator_app/src/main.cpp
Labels: bug
