Repository openDAQ/openDAQ, pull requests merged in 2024-04, with the labels that each got.

#242 Fix annoying and unspecific "Not Found" error on device startup
  core/opendaq/opendaq/src/instance_impl.cpp
Labels: enhancement

#243 Forward only changed descriptors in streaming LT
  core/opendaq/signal/include/opendaq/signal_impl.h
  modules/tests/test_opendaq_device_modules/test_streaming.cpp
  shared/libraries/websocket_streaming/include/websocket_streaming/input_signal.h
  shared/libraries/websocket_streaming/include/websocket_streaming/streaming_client.h
  shared/libraries/websocket_streaming/src/input_signal.cpp
  shared/libraries/websocket_streaming/src/streaming_client.cpp
Labels: bug

#248 Fix MSVC Win32 build
  core/opendaq/device/tests/test_device_info.cpp
  core/opendaq/reader/tests/test_multi_reader.cpp
  core/opendaq/signal/tests/test_data_packet.cpp
  core/opendaq/signal/tests/test_signal.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
Labels: bug

#252 Change discovery priority order
  core/opendaq/device/include/opendaq/server_capability.h
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
Labels: bug

#251 Fix `server_capability.h` and `server_capability_config.h` bindings
  core/opendaq/device/include/opendaq/server_capability.h
  core/opendaq/device/include/opendaq/server_capability_config.h
Labels: bug

#250 Add simple FFT function block + fix block reader
  core/opendaq/reader/include/opendaq/block_reader_impl.h
  core/opendaq/reader/src/block_reader_impl.cpp
  external/CMakeLists.txt
  external/kissfft/CMakeLists.txt
  external/kissfft/_kiss_fft_guts.h
  external/kissfft/kiss_fft.c
  external/kissfft/kiss_fft.h
  external/kissfft/kiss_fft_log.h
  modules/ref_fb_module/include/ref_fb_module/fft_fb_impl.h
  modules/ref_fb_module/src/CMakeLists.txt
  modules/ref_fb_module/src/fft_fb_impl.cpp
  modules/ref_fb_module/src/ref_fb_module_impl.cpp
  modules/ref_fb_module/tests/test_ref_fb_module.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
Labels: bug, enhancement

#249 renderer: limit labels on x-axis
  core/opendaq/reader/include/opendaq/reader_impl.h
  core/opendaq/reader/src/multi_reader_impl.cpp
  core/opendaq/reader/src/stream_reader_impl.cpp
  modules/ref_fb_module/include/ref_fb_module/classifier_fb_impl.h
  modules/ref_fb_module/src/classifier_fb_impl.cpp
  modules/ref_fb_module/src/renderer_fb_impl.cpp
Labels: enhancement

#256 Fix serial number in simulator
  simulator/Vagrantfile
  simulator/configurator.py
  simulator/opendaq-config.json
  simulator/simulator.service
Labels: bug

#270 Update ui-bundle version (Antora)
  antora-playbook-dev.yml
  antora-playbook.yml
Labels: bug, documentation

#220 Add getLastValue support over native when no streaming is available
  core/opendaq/opendaq/mocks/include/opendaq/gmock/streaming.h
  core/opendaq/opendaq/tests/test_instance.cpp
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/streaming/include/opendaq/mirrored_signal_impl.h
  core/opendaq/streaming/include/opendaq/mirrored_signal_private.h
  modules/tests/test_ref_modules/test_ref_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_signal_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_server_signal.h
  shared/libraries/config_protocol/src/CMakeLists.txt
  shared/libraries/config_protocol/src/config_protocol_client.cpp
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
  shared/libraries/config_protocol/tests/test_utils.cpp
Labels: enhancement

#238 Update getLastValue docs
  bindings/python/tests/CMakeLists.txt
  bindings/python/tests/test_core_type_integer.py
  bindings/python/tests/test_how_to_last_value.py
  core/opendaq/signal/include/opendaq/data_packet.h
  core/opendaq/signal/include/opendaq/signal.h
  docs/Antora/modules/howto_guides/pages/howto.adoc
  docs/Antora/modules/howto_guides/pages/howto_measure_single_value.adoc
  docs/tests/CMakeLists.txt
  docs/tests/test_get_last_value.cpp
Labels: documentation

#272 Update streaming howto-s and glossary
  docs/Antora/modules/background_info/pages/streaming.adoc
  docs/Antora/modules/glossary/pages/glossary.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_streaming.adoc
Labels: documentation

#282 Change `IPermissions` and `IPermissionsBuilder` to fix Delphi bindings
  changelog/changelog_3.0.0-4.0.0.txt
  core/coreobjects/include/coreobjects/permissions.h
  core/coreobjects/include/coreobjects/permissions_builder.h
  core/coreobjects/include/coreobjects/permissions_builder_impl.h
  core/coreobjects/src/permissions_builder_impl.cpp
  core/coreobjects/tests/test_permission_manager.cpp
  core/coreobjects/tests/test_permissions_builder.cpp
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/opendaq/tests/test_access_control.cpp
Labels: bug, bindings:delphi

#285 Fixed license header error for 2 ping library files (exclusions) and give fixing hint in check_headers.yml
  .github/workflows/check_headers.yml
  shared/tools/license-header-checker/ignore-filter.txt
Labels: ci

#273 Docs check how-tos
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqHowToGuidesTests.cs
  bindings/python/tests/test_how_to.py
  bindings/python/tests/test_how_to_add_function_block.py
  bindings/python/tests/test_how_to_last_value.py
  core/opendaq/reader/src/reader_status_impl.cpp
  docs/Antora/modules/ROOT/pages/introduction.adoc
  docs/Antora/modules/background_info/nav-background_info.adoc
  docs/Antora/modules/background_info/pages/data_path.adoc
  docs/Antora/modules/background_info/pages/property_system.adoc
  docs/Antora/modules/background_info/pages/signals.adoc
  docs/Antora/modules/getting_started/pages/quick_start.adoc
  docs/Antora/modules/getting_started/pages/quick_start_application.adoc
  docs/Antora/modules/howto_guides/nav-howto-guides.adoc
  docs/Antora/modules/howto_guides/pages/howto.adoc
  docs/Antora/modules/howto_guides/pages/howto_add_function_block.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_function_block.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_instance.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_instance_providers.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_streaming.adoc
  docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
  docs/Antora/modules/howto_guides/pages/howto_measure_single_value.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_aligned_signals.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_last_n_samples.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_domain.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timeouts.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timestamps.adoc
  docs/Antora/modules/howto_guides/pages/howto_save_load_configuration.adoc
  docs/tests/CMakeLists.txt
  docs/tests/test_config_provider.cpp
  docs/tests/test_get_last_value.cpp
  docs/tests/test_howto.cpp
  docs/tests/test_howto_configure_instance.cpp
  docs/tests/test_streaming_config.cpp
  examples/cpp/multi_reader_example/multi_reader_example.cpp
  examples/cpp/reader_basics_example/reader_basics_example.cpp
  examples/cpp/reader_timeouts_example/reader_timeouts_example.cpp
  examples/cpp/reader_with_time_stamps/reader_with_time_stamps.cpp
  examples/cpp/streaming_configuration_example/streaming_configuration_example.cpp
  examples/cpp/tail_reader_example/tail_reader_example.cpp
Labels: documentation

#286 Merge branch 'release/3.0' into 'main'
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqHowToGuidesTests.cs
  bindings/python/tests/test_how_to.py
  bindings/python/tests/test_how_to_add_function_block.py
  bindings/python/tests/test_how_to_last_value.py
  core/opendaq/reader/src/reader_status_impl.cpp
  docs/Antora/modules/ROOT/pages/introduction.adoc
  docs/Antora/modules/background_info/nav-background_info.adoc
  docs/Antora/modules/background_info/pages/data_path.adoc
  docs/Antora/modules/background_info/pages/property_system.adoc
  docs/Antora/modules/background_info/pages/signals.adoc
  docs/Antora/modules/getting_started/pages/quick_start.adoc
  docs/Antora/modules/getting_started/pages/quick_start_application.adoc
  docs/Antora/modules/howto_guides/nav-howto-guides.adoc
  docs/Antora/modules/howto_guides/pages/howto.adoc
  docs/Antora/modules/howto_guides/pages/howto_add_function_block.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_function_block.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_instance.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_instance_providers.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_streaming.adoc
  docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
  docs/Antora/modules/howto_guides/pages/howto_measure_single_value.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_aligned_signals.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_last_n_samples.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_domain.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timeouts.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timestamps.adoc
  docs/Antora/modules/howto_guides/pages/howto_save_load_configuration.adoc
  docs/tests/CMakeLists.txt
  docs/tests/test_config_provider.cpp
  docs/tests/test_get_last_value.cpp
  docs/tests/test_howto.cpp
  docs/tests/test_howto_configure_instance.cpp
  docs/tests/test_streaming_config.cpp
  examples/cpp/multi_reader_example/multi_reader_example.cpp
  examples/cpp/reader_basics_example/reader_basics_example.cpp
  examples/cpp/reader_timeouts_example/reader_timeouts_example.cpp
  examples/cpp/reader_with_time_stamps/reader_with_time_stamps.cpp
  examples/cpp/streaming_configuration_example/streaming_configuration_example.cpp
  examples/cpp/tail_reader_example/tail_reader_example.cpp
Labels: documentation

#287 Fix require tags filter
  core/opendaq/component/src/search_filter_impl.cpp
  core/opendaq/component/tests/CMakeLists.txt
  core/opendaq/component/tests/test_search_filter.cpp
Labels: bug

#280 quick start guide update
  core/opendaq/reader/src/stream_reader_impl.cpp
  docs/Antora/modules/background_info/pages/device.adoc
  docs/Antora/modules/background_info/pages/modules.adoc
  docs/Antora/modules/background_info/pages/property_system.adoc
  docs/Antora/modules/background_info/pages/streaming.adoc
  docs/Antora/modules/getting_started/pages/quick_start_application.adoc
  docs/Antora/modules/glossary/pages/glossary.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_instance.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_streaming.adoc
  docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_last_n_samples.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_domain.adoc
  examples/cpp/client_discovery/client_discovery.cpp
  examples/cpp/client_local/client_local.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
Labels: documentation

#281 Supporting connection with ipv6 connection string
  bindings/python/opendaq/generated/device/py_server_capability.cpp
  bindings/python/opendaq/generated/opendaq/py_instance_builder.cpp
  bindings/python/opendaq/generated/reader/py_block_reader_status.cpp
  changelog/changelog_3.0.0-4.0.0.txt
  core/opendaq/device/include/opendaq/server_capability.h
  core/opendaq/device/include/opendaq/server_capability_config.h
  core/opendaq/device/include/opendaq/server_capability_impl.h
  core/opendaq/device/src/server_capability_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/native_streaming_client_module/tests/test_native_streaming_client_module.cpp
  modules/opcua_client_module/src/opcua_client_module_impl.cpp
  modules/opcua_client_module/tests/test_opcua_client_module.cpp
  modules/tests/test_opendaq_device_modules/CMakeLists.txt
  modules/tests/test_opendaq_device_modules/test_helpers.h
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_streaming.cpp
  modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
  modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
  modules/websocket_streaming_client_module/tests/test_websocket_streaming_client_module.cpp
Labels: enhancement

#295 refactor connection doc
  docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
Labels: documentation
