Repository openDAQ/openDAQ, pull requests merged in 2024-05, with the labels that each got.

#293 Allow overriding required Boost component libraries when building source Boost
  external/boost/CMakeLists.txt
Labels: bug, enhancement

#300 Fix memory leak in ListPtr::toVector
  core/corecontainers/include/coretypes/listptr.h
  core/coretypes/tests/test_listobject.cpp
Labels: bug

#292 Clone property object to create default config from type
  bindings/python/core_objects/generated/py_component_type.cpp
  changelog/changelog_3.0.0-4.0.0.txt
  core/coreobjects/include/coreobjects/component_type.h
  core/coreobjects/include/coreobjects/component_type_impl.h
  core/opendaq/device/include/opendaq/device_type.h
  core/opendaq/device/include/opendaq/device_type_factory.h
  core/opendaq/device/include/opendaq/device_type_impl.h
  core/opendaq/device/src/device_type_impl.cpp
  core/opendaq/functionblock/include/opendaq/function_block_type.h
  core/opendaq/functionblock/include/opendaq/function_block_type_factory.h
  core/opendaq/functionblock/include/opendaq/function_block_type_impl.h
  core/opendaq/functionblock/src/function_block_type_impl.cpp
  core/opendaq/functionblock/tests/test_function_block.cpp
  core/opendaq/opendaq/mocks/mock_device_module.cpp
  core/opendaq/opendaq/mocks/mock_fb_module.cpp
  core/opendaq/server/include/opendaq/server_type.h
  core/opendaq/server/include/opendaq/server_type_factory.h
  core/opendaq/server/include/opendaq/server_type_impl.h
  core/opendaq/server/src/server_type_impl.cpp
  core/opendaq/server/tests/test_server_type.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
  modules/opcua_server_module/src/opcua_server_impl.cpp
  modules/ref_fb_module/src/statistics_fb_impl.cpp
  modules/ref_fb_module/src/trigger_fb_impl.cpp
  modules/websocket_streaming_server_module/src/websocket_streaming_server_impl.cpp
  shared/libraries/config_protocol/tests/test_config_client_server.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_function_block_type.cpp
  shared/libraries/testutils/src/test_comparators.cpp
Labels: enhancement

#305 Fix - set start time param of linear rule to 0 for streaming-lt signals
  shared/libraries/websocket_streaming/src/signal_descriptor_converter.cpp
  shared/libraries/websocket_streaming/tests/test_signal_descriptor_converter.cpp
Labels: bug

#290 [TBBAS-1286] Python GUI App redesign
  bindings/python/package/build_pip.py
  examples/python/gui_demo.py
  examples/python/gui_demo/__init__.py
  examples/python/gui_demo/app_context.py
  examples/python/gui_demo/components/__init__.py
  examples/python/gui_demo/components/add_device_dialog.py
  examples/python/gui_demo/components/add_function_block_dialog.py
  examples/python/gui_demo/components/attributes_dialog.py
  examples/python/gui_demo/components/block_view.py
  examples/python/gui_demo/components/diaolog.py
  examples/python/gui_demo/components/input_port_row_view.py
  examples/python/gui_demo/components/input_ports_view.py
  examples/python/gui_demo/components/output_signal_row.py
  examples/python/gui_demo/components/output_signals_view.py
  examples/python/gui_demo/components/properties_view.py
  examples/python/gui_demo/event_port.py
  examples/python/gui_demo/icons/channel.png
  examples/python/gui_demo/icons/circle.png
  examples/python/gui_demo/icons/device.png
  examples/python/gui_demo/icons/down.png
  examples/python/gui_demo/icons/folder.png
  examples/python/gui_demo/icons/function_block.png
  examples/python/gui_demo/icons/input_port.png
  examples/python/gui_demo/icons/link.png
  examples/python/gui_demo/icons/right.png
  examples/python/gui_demo/icons/settings.png
  examples/python/gui_demo/icons/signal.png
  examples/python/gui_demo/icons/unlink.png
  examples/python/gui_demo/utils.py
Labels: enhancement, bindings:python

#316 Fix native protocol inactivity timeout handling
  shared/libraries/native_streaming_protocol/src/base_session_handler.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
Labels: bug

#306 Sync device name and location with device info
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/include/opendaq/device_info.h
  core/opendaq/device/include/opendaq/device_info_config.h
  core/opendaq/device/include/opendaq/device_info_impl.h
  core/opendaq/device/include/opendaq/server_capability.h
  core/opendaq/device/src/device_info_impl.cpp
  core/opendaq/device/tests/test_device.cpp
  core/opendaq/device/tests/test_device_info.cpp
  core/opendaq/opendaq/mocks/mock_physical_device.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_device_impl.cpp
  modules/opcua_client_module/src/opcua_client_module_impl.cpp
  modules/ref_device_module/src/ref_device_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_streaming.cpp
  modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_folder_impl.h
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
  shared/libraries/config_protocol/tests/test_utils.cpp
  shared/libraries/config_protocol/tests/test_utils.h
  shared/libraries/discovery/src/daq_discovery_client.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
  shared/libraries/websocket_streaming/src/websocket_client_device_impl.cpp
Labels: bug, enhancement

#317 Fix native protocol inactivity timeout handling - release patch
  shared/libraries/native_streaming_protocol/src/base_session_handler.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
Labels: bug

#319 Fixed regression in `deploy.yml`
  .github/workflows/deploy.yml
Labels: ci

#321 Implement blocks overlapping in BlockReader
  core/opendaq/reader/include/opendaq/block_reader.h
  core/opendaq/reader/include/opendaq/block_reader_builder.h
  core/opendaq/reader/include/opendaq/block_reader_builder_impl.h
  core/opendaq/reader/include/opendaq/block_reader_impl.h
  core/opendaq/reader/include/opendaq/reader_factory.h
  core/opendaq/reader/src/CMakeLists.txt
  core/opendaq/reader/src/block_reader_builder_impl.cpp
  core/opendaq/reader/src/block_reader_impl.cpp
  core/opendaq/reader/tests/test_block_reader.cpp
Labels: enhancement

#329 Add client connection configuration info in the device info
  bindings/python/opendaq/generated/device/py_device_info.cpp
  changelog/changelog_3.0.0-4.0.0.txt
  core/opendaq/device/include/opendaq/device_info.h
  core/opendaq/device/include/opendaq/device_info_impl.h
  core/opendaq/device/include/opendaq/server_capability.h
  core/opendaq/device/include/opendaq/server_capability_config.h
  core/opendaq/device/include/opendaq/server_capability_impl.h
  core/opendaq/device/src/device_info_impl.cpp
  core/opendaq/device/src/server_capability_impl.cpp
  core/opendaq/device/tests/test_device_info.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/native_streaming_client_module/tests/test_native_streaming_client_module.cpp
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
  modules/opcua_client_module/src/opcua_client_module_impl.cpp
  modules/opcua_client_module/tests/test_opcua_client_module.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
  modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
  modules/websocket_streaming_client_module/tests/test_websocket_streaming_client_module.cpp
  shared/libraries/opcuatms/opcuatms_server/src/tms_server.cpp
  shared/libraries/websocket_streaming/src/websocket_streaming_server.cpp
Labels: enhancement
