Repository openDAQ/openDAQ, pull requests merged in 2024-07, with the labels that each got.

#352 <TBBAS-1425> Enable streaming for signals of FB added via OpcUa
  examples/python/gui_demo/components/input_port_row_view.py
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_device.cpp
Labels: bug

#356 Quick start guide update
  docs/Antora/modules/getting_started/pages/quick_start_application.adoc
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_cpp.adoc
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
  examples/cpp/quick_start/quick_start_full.cpp
  examples/cpp/quick_start/quick_start_simulator.cpp
  examples/python/guide/quick_start_application.py
  examples/python/guide/simulator.py
  modules/ref_device_module/include/ref_device_module/ref_device_impl.h
  modules/ref_device_module/src/ref_device_impl.cpp
  modules/ref_device_module/src/ref_device_module_impl.cpp
Labels: documentation

#360 Update yum .repo files to vault.centos.org
  .github/workflows/deploy.yml
Labels: bug

#364 Re-add check for signal parent component
  core/opendaq/opendaq/mocks/include/opendaq/mock/mock_fb.h
  core/opendaq/opendaq/mocks/mock_fb.cpp
  core/opendaq/signal/include/opendaq/signal_container_impl.h
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_function_block.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_function_block.cpp
Labels: bug

#363 Remove acceptsConnectionParameters from module
  bindings/python/opendaq/generated/modulemanager/py_module.cpp
  changelog/changelog_3.0.0-4.0.0.txt
  core/opendaq/device/include/opendaq/device_type.h
  core/opendaq/device/include/opendaq/device_type_factory.h
  core/opendaq/device/include/opendaq/device_type_impl.h
  core/opendaq/device/src/device_type_impl.cpp
  core/opendaq/device/tests/test_device.cpp
  core/opendaq/device/tests/test_device_info.cpp
  core/opendaq/modulemanager/include/opendaq/module.h
  core/opendaq/modulemanager/include/opendaq/module_impl.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/modulemanager/tests/mock/mock_module.cpp
  core/opendaq/modulemanager/tests/mock/mock_module.h
  core/opendaq/opendaq/mocks/include/opendaq/mock/mock_device_module.h
  core/opendaq/opendaq/mocks/include/opendaq/mock/mock_fb_module.h
  core/opendaq/opendaq/mocks/include/opendaq/mock/mock_server_module.h
  core/opendaq/opendaq/mocks/mock_device_module.cpp
  core/opendaq/opendaq/mocks/mock_fb_module.cpp
  core/opendaq/opendaq/mocks/mock_server_module.cpp
  core/opendaq/opendaq/tests/test_access_control.cpp
  core/opendaq/opendaq/tests/test_core_events.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
  modules/audio_device_module/include/audio_device_module/audio_device_module_impl.h
  modules/audio_device_module/src/audio_device_impl.cpp
  modules/audio_device_module/src/audio_device_module_impl.cpp
  modules/audio_device_module/tests/test_audio_device_module.cpp
  modules/empty_module/tests/test_empty_module.cpp
  modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/native_streaming_client_module/tests/test_native_streaming_client_module.cpp
  modules/opcua_client_module/include/opcua_client_module/opcua_client_module_impl.h
  modules/opcua_client_module/src/opcua_client_module_impl.cpp
  modules/opcua_client_module/tests/test_opcua_client_module.cpp
  modules/ref_device_module/include/ref_device_module/ref_device_module_impl.h
  modules/ref_device_module/src/ref_device_impl.cpp
  modules/ref_device_module/src/ref_device_module_impl.cpp
  modules/ref_device_module/tests/test_ref_device_module.cpp
  modules/ref_fb_module/tests/test_ref_fb_module.cpp
  modules/tests/test_opendaq_device_modules/test_helpers/mock_helper_module.cpp
  modules/tests/test_opendaq_device_modules/test_helpers/mock_helper_module.h
  modules/tests/test_opendaq_device_modules/test_streaming.cpp
  modules/websocket_streaming_client_module/include/websocket_streaming_client_module/websocket_streaming_client_module_impl.h
  modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
  modules/websocket_streaming_client_module/tests/test_websocket_streaming_client_module.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_helpers.h
  shared/libraries/opcuatms/tests/opcuatms_integration/test_streaming_integration.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_integration.cpp
  shared/libraries/websocket_streaming/tests/streaming_test_helpers.h
Labels: enhancement

#371 Update CoreTypes Delphi bindings
  core/coretypes/bindings/delphi/OpenDAQ.CoreTypes.pas
  core/coretypes/bindings/delphi/OpenDAQ.Deserializer.pas
  core/coretypes/bindings/delphi/OpenDAQ.Exceptions.pas
  core/coretypes/bindings/delphi/OpenDAQ.FunctionImpl.pas
  core/coretypes/bindings/delphi/OpenDAQ.Number.pas
  core/coretypes/bindings/delphi/OpenDAQ.ObjectPtr.pas
  core/coretypes/bindings/delphi/OpenDAQ.ProcedureImpl.pas
  core/coretypes/bindings/delphi/OpenDAQ.ProxyValue.pas
  core/coretypes/bindings/delphi/OpenDAQ.SerializedList.pas
  core/coretypes/bindings/delphi/OpenDAQ.SerializedObject.pas
  core/coretypes/bindings/delphi/OpenDAQ.Serializer.pas
  core/coretypes/bindings/delphi/OpenDAQ.TSampleType.pas
  core/coretypes/bindings/delphi/OpenDAQ.TString.pas
  core/coretypes/bindings/delphi/OpenDAQ.Updatable.pas
  core/coretypes/bindings/delphi/OpenDAQ.VersionInfo.pas
Labels: bindings:delphi

#372 Fix MSVC 2017 Win32 compilation
  core/opendaq/reader/tests/test_block_reader.cpp
  core/opendaq/reader/tests/test_multi_reader.cpp
  modules/tests/test_opendaq_device_modules/test_default_config.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
Labels: bug

#373 Force Node 16 usage in Manylinux CI
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/package.yml
Labels: bug, ci

#369 Make ref device options parsing consistent
  core/opendaq/opendaq/tests/test_config_provider.h
  modules/ref_device_module/include/ref_device_module/common.h
  modules/ref_device_module/include/ref_device_module/ref_device_impl.h
  modules/ref_device_module/src/ref_device_impl.cpp
  modules/ref_device_module/src/ref_device_module_impl.cpp
  modules/ref_device_module/tests/test_ref_device_module.cpp
  modules/tests/test_ref_modules/test_ref_modules.cpp
  simulator/configurator.py
  simulator/opendaq-config.json
Labels: bug

#391 Fix native server shutdown process
  external/native_streaming/CMakeLists.txt
  modules/native_streaming_server_module/include/native_streaming_server_module/native_streaming_server_impl.h
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
Labels: bug

#388 Add client disconnection handling by LT-server
  shared/libraries/websocket_streaming/include/websocket_streaming/streaming_server.h
  shared/libraries/websocket_streaming/src/streaming_server.cpp
  shared/libraries/websocket_streaming/tests/test_streaming.cpp
Labels: bug

#386 Handle client disconnection on the LT-streaming server
  shared/libraries/websocket_streaming/include/websocket_streaming/streaming_server.h
  shared/libraries/websocket_streaming/src/streaming_server.cpp
  shared/libraries/websocket_streaming/tests/test_streaming.cpp
Labels: bug

#389 [TBBAS-1717] Python GUI App: displaying custom components in full topology view
  examples/python/gui_demo.py
  examples/python/gui_demo/app_context.py
  examples/python/gui_demo/components/block_view.py
Labels: enhancement, bindings:python

#366 Fix stream reader raw data read and add skip samples method
  bindings/python/opendaq/generated/reader/py_stream_reader.cpp
  core/opendaq/reader/include/opendaq/stream_reader.h
  core/opendaq/reader/include/opendaq/stream_reader_impl.h
  core/opendaq/reader/src/stream_reader_impl.cpp
  core/opendaq/reader/tests/test_stream_reader.cpp
Labels: bug, enhancement

#390 [TBBAS-1716] Python GUI App: short_id generating bugfix
  examples/python/gui_demo/app_context.py
Labels: bug, bindings:python

#392 Fix event packet caching in native streaming:
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
  shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
Labels: bug

#387 Add configuration matrix for arm64
  .github/workflows/deploy.yml
  .github/workflows/package.yml
  cmake/Packing.cmake
Labels: ci

#395 Fix property object invalid cast on clone
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/opendaq/device/include/opendaq/address_info_impl.h
  core/opendaq/device/include/opendaq/server_capability_impl.h
  core/opendaq/device/src/address_info_impl.cpp
  core/opendaq/device/src/server_capability_impl.cpp
Labels: bug

#394 opendaq_dependency: fix target checks and better target suport
  external/opendaq_dependency.cmake
  external/taskflow/CMakeLists.txt
  external/xxHash/CMakeLists.txt
Labels: enhancement

#398 Bump `ui-bundle.zip` version of `antora-ui-spring` from release 1.3 to 1.4
  antora-playbook-dev.yml
  antora-playbook.yml
  antora-specs-playbook-dev.yml
  antora-specs-playbook.yml
Labels: bug, documentation

#401 Fix deploy step
  .github/workflows/deploy.yml
Labels: ci

#403 [TBBAS-1725] Python GUI App fix displaying values with spaces
  examples/python/gui_demo.py
  examples/python/gui_demo/components/attributes_dialog.py
  examples/python/gui_demo/components/properties_view.py
Labels: bug

#410 Fix native transport layer properties config parsing
  modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
Labels: bug

#413 Python bindings: Fix segfault in readers
  bindings/python/opendaq/generated/reader/py_multi_reader.cpp
  bindings/python/opendaq/generated/reader/py_stream_reader.cpp
  bindings/python/tests/test_reader_datetime.py
Labels: bug, bindings:python

#418 Fix docs link
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
Labels: documentation

#422 Create and install openDAQ config version cmake
  CMakeLists.txt
Labels: bug

#421 Set default module suffix in opendaq package
  cmake/openDAQConfig.cmake.in
Labels: bug
