Repository openDAQ/openDAQ, pull requests merged in 2024-06, with the labels that each got.

#313 Other/opendaq component merge
  app/test_app/src/CMakeLists.txt
  bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/OpenDAQ_CITests.cs
  cmake/DaqComponents.cmake
  cmake/DaqInternal.cmake
  cmake/RTGen.cmake
  cmake/openDAQConfig.cmake.in
  core/coreobjects/src/CMakeLists.txt
  core/opendaq/CMakeLists.txt
  core/opendaq/component/CMakeLists.txt
  core/opendaq/component/src/CMakeLists.txt
  core/opendaq/context/CMakeLists.txt
  core/opendaq/context/src/CMakeLists.txt
  core/opendaq/context/src/empty.cpp
  core/opendaq/device/CMakeLists.txt
  core/opendaq/device/src/CMakeLists.txt
  core/opendaq/device/tests/CMakeLists.txt
  core/opendaq/functionblock/CMakeLists.txt
  core/opendaq/functionblock/src/CMakeLists.txt
  core/opendaq/functionblock/tests/CMakeLists.txt
  core/opendaq/logger/CMakeLists.txt
  core/opendaq/logger/src/CMakeLists.txt
  core/opendaq/modulemanager/CMakeLists.txt
  core/opendaq/modulemanager/include/opendaq/format.h
  core/opendaq/modulemanager/include/opendaq/icmp_header.h
  core/opendaq/modulemanager/include/opendaq/icmp_ping.h
  core/opendaq/modulemanager/include/opendaq/ipv4_header.h
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/src/CMakeLists.txt
  core/opendaq/modulemanager/src/icmp_header.cpp
  core/opendaq/modulemanager/src/icmp_ping.cpp
  core/opendaq/modulemanager/src/ipv4_header.cpp
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/modulemanager/tests/CMakeLists.txt
  core/opendaq/modulemanager/tests/mock/CMakeLists.txt
  core/opendaq/opendaq/CMakeLists.txt
  core/opendaq/opendaq/mocks/CMakeLists.txt
  core/opendaq/opendaq/src/CMakeLists.txt
  core/opendaq/opendaq/tests/CMakeLists.txt
  core/opendaq/reader/CMakeLists.txt
  core/opendaq/reader/src/CMakeLists.txt
  core/opendaq/scheduler/CMakeLists.txt
  core/opendaq/scheduler/src/CMakeLists.txt
  core/opendaq/scheduler/tests/CMakeLists.txt
  core/opendaq/server/CMakeLists.txt
  core/opendaq/server/src/CMakeLists.txt
  core/opendaq/signal/CMakeLists.txt
  core/opendaq/signal/src/CMakeLists.txt
  core/opendaq/streaming/CMakeLists.txt
  core/opendaq/streaming/src/CMakeLists.txt
  core/opendaq/utility/CMakeLists.txt
  core/opendaq/utility/src/CMakeLists.txt
  shared/libraries/CMakeLists.txt
  shared/libraries/config_protocol/src/CMakeLists.txt
  shared/libraries/discovery_server/src/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_client/src/CMakeLists.txt
  shared/libraries/ping/CMakeLists.txt
  shared/libraries/ping/src/CMakeLists.txt
  shared/libraries/signal_generator/src/CMakeLists.txt
  shared/libraries/websocket_streaming/src/CMakeLists.txt
Labels: enhancement

#337 Regression tests
  .github/workflows/ci.yml
  .github/workflows/regression_simulator_generator.yml
  CMakeLists.txt
  docs/Antora/modules/glossary/pages/glossary.adoc
  regression/CMakeLists.txt
  regression/CMakeListsTop.txt
  regression/simulator/CMakeLists.txt
  regression/simulator/regression_simulator.cpp
  regression/tests/CMakeLists.txt
  regression/tests/reg_p_test_channel.cpp
  regression/tests/reg_p_test_component.cpp
  regression/tests/reg_p_test_device.cpp
  regression/tests/reg_p_test_fb.cpp
  regression/tests/reg_p_test_folder.cpp
  regression/tests/reg_p_test_input_port.cpp
  regression/tests/reg_p_test_property.cpp
  regression/tests/reg_p_test_signal.cpp
  regression/tests/setup_regression.h
  regression/tests/test_app.cpp
Labels: enhancement, ci

#336 Bump version of `antora-ui-spring`
  antora-playbook-dev.yml
  antora-playbook.yml
Labels: documentation

#338 Only perform regression tests when AWS secrets are available
  .github/workflows/ci.yml
Labels: bug, ci

#341 Downgrade benjlevesque/short-sha
  .github/workflows/deploy.yml
Labels: bug, ci

#346 Rename instance builder discovery service add/get into add/get "server"
  bindings/python/opendaq/generated/device/py_device.cpp
  bindings/python/opendaq/generated/device/py_device_info.cpp
  bindings/python/opendaq/generated/device/py_device_type.cpp
  bindings/python/opendaq/generated/device/py_server_capability.cpp
  bindings/python/opendaq/generated/modulemanager/py_module.cpp
  bindings/python/opendaq/generated/opendaq/py_instance_builder.cpp
  bindings/python/opendaq/generated/signal/py_event_packet.cpp
  bindings/python/opendaq/generated/streaming/py_mirrored_signal_private.cpp
  bindings/python/opendaq/generated/streaming/py_streaming_type.cpp
  changelog/changelog_3.0.0-4.0.0.txt
  core/opendaq/context/include/opendaq/context.h
  core/opendaq/modulemanager/include/opendaq/context_factory.h
  core/opendaq/opendaq/include/opendaq/instance_builder.h
  core/opendaq/opendaq/include/opendaq/instance_builder_impl.h
  core/opendaq/opendaq/src/instance_builder_impl.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
  examples/cpp/quick_start/quick_start_simulator.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
  simulator/simulator_app/src/main.cpp
Labels: bug

#347 Group devices with 1 server capability
  core/opendaq/modulemanager/src/module_manager_impl.cpp
Labels: bug

#353 Fix race condition within LT-streaming on signal unsubscribe:
  shared/libraries/websocket_streaming/include/websocket_streaming/output_signal.h
  shared/libraries/websocket_streaming/include/websocket_streaming/streaming_server.h
  shared/libraries/websocket_streaming/src/output_signal.cpp
  shared/libraries/websocket_streaming/src/streaming_server.cpp
  shared/libraries/websocket_streaming/src/websocket_streaming_server.cpp
  shared/libraries/websocket_streaming/tests/test_streaming.cpp
  shared/libraries/websocket_streaming/tests/test_websocket_client_device.cpp
Labels: bug

#327 <TBBAS-1402> Add native client identification mechanism
  modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h
  modules/native_streaming_client_module/src/CMakeLists.txt
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/client_session_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_client_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_protocol_types.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/server_session_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/subscribers_registry.h
  shared/libraries/native_streaming_protocol/src/CMakeLists.txt
  shared/libraries/native_streaming_protocol/src/client_session_handler.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
  shared/libraries/native_streaming_protocol/src/server_session_handler.cpp
  shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
  shared/libraries/native_streaming_protocol/src/subscribers_registry.cpp
  shared/libraries/native_streaming_protocol/tests/test_base.h
  shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
Labels: enhancement
