Repository openDAQ/openDAQ, pull requests merged in 2024-10, with the labels that each got.

#524 Simulator CI build error fix
  .github/workflows/deploy.yml
Labels: bug, ci

#522 Fix `spdlog` dependency
  .github/pull_request_template.md
  cmake/openDAQConfig.cmake.in
  docs/Antora/modules/howto_guides/pages/howto.adoc
Labels: bug

#526 Change event mutex to recursive
  core/coreobjects/tests/test_value_changed_events.cpp
  core/coretypes/include/coretypes/event_impl.h
Labels: bug

#529 Disable config client property object onWrite/Read events
  changelog/changelog_3.0.0-4.0.0.txt
  shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
  shared/libraries/config_protocol/include/config_protocol/errors.h
  shared/libraries/config_protocol/include/config_protocol/exceptions.h
  shared/libraries/config_protocol/src/CMakeLists.txt
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
Labels: bug

#531 Fix enumeration factory with integer parameter
  core/coreobjects/tests/test_property_object.cpp
  core/coretypes/src/enumeration_impl.cpp
Labels: bug

#525 Implement concurrent config connections limit for native server
  changelog/changelog_3.0.0-4.0.0.txt
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/opendaq/include/opendaq/errors.h
  core/opendaq/opendaq/include/opendaq/exceptions.h
  docs/tests/test_modules.cpp
  external/native_streaming/CMakeLists.txt
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
  modules/native_streaming_server_module/tests/test_native_streaming_server_module.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_server.h
  shared/libraries/config_protocol/src/config_protocol.cpp
  shared/libraries/config_protocol/src/config_protocol_client.cpp
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/config_protocol/tests/test_config_client_server.cpp
  shared/libraries/config_protocol/tests/test_config_packet.cpp
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/server_session_handler.h
  shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
  shared/libraries/native_streaming_protocol/src/server_session_handler.cpp
  shared/libraries/native_streaming_protocol/tests/test_client_to_dev_streaming.cpp
  shared/libraries/native_streaming_protocol/tests/test_config_packets.cpp
  shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
Labels: enhancement

#530 Enable protected write calls over OPC UA
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_property_object_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property_object.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_device.cpp
  shared/libraries/opcuatms/opcuatms_server/tests/test_tms_property_object.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_property_object.cpp
Labels: bug

#535 Fix native device processing threads terminating on connection exception
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
Labels: bug

#534 Add an option to restore client-side configuration on reconnection
  core/opendaq/streaming/include/opendaq/streaming_impl.h
  core/opendaq/streaming/tests/test_streaming.cpp
  modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/tests/test_core_events.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
Labels: enhancement

#537 Stop sorting properties by name in python GUI
  examples/python/gui_demo/components/properties_view.py
Labels: bug, bindings:python

#517 [TBBAS-1612] Support modeling nested function blocks
  bindings/python/opendaq/generated/functionblock/py_function_block.cpp
  changelog/changelog_3.0.0-4.0.0.txt
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/functionblock/include/opendaq/channel_impl.h
  core/opendaq/functionblock/include/opendaq/function_block.h
  core/opendaq/functionblock/include/opendaq/function_block_impl.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/function_block.h
  core/opendaq/opendaq/mocks/include/opendaq/mock/mock_fb.h
  core/opendaq/opendaq/mocks/mock_fb.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
  docs/Antora/modules/howto_guides/pages/howto_save_load_configuration.adoc
  modules/ref_fb_module/include/ref_fb_module/statistics_fb_impl.h
  modules/ref_fb_module/src/statistics_fb_impl.cpp
  modules/ref_fb_module/tests/test_fb_statistics.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
Labels: enhancement, Integration breaking

#541 [TBBAS-1812][TBBAS-1817] Python GUI improvements
  examples/python/gui_demo.py
  examples/python/gui_demo/app_context.py
  examples/python/gui_demo/components/add_config_dialog.py
  examples/python/gui_demo/components/add_device_dialog.py
  examples/python/gui_demo/components/add_function_block_dialog.py
  examples/python/gui_demo/components/attributes_dialog.py
  examples/python/gui_demo/components/block_view.py
  examples/python/gui_demo/components/dialog.py
  examples/python/gui_demo/components/input_port_row_view.py
  examples/python/gui_demo/components/load_instance_config_dialog.py
  examples/python/gui_demo/components/output_signal_row.py
  examples/python/gui_demo/components/properties_view.py
Labels: enhancement, bindings:python

#543 Add Reference Domain Info description to Data Descriptor Doxygen brief
  core/opendaq/signal/include/opendaq/data_descriptor.h
Labels: documentation

#520 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/1-BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/2-FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/3-QUESTION.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#528 Add missing RPCs (remote procedure calls)
  bindings/dotnet/openDAQ.Net/openDAQDemo.Net/openDAQDemo.Net.csproj
  core/opendaq/device/include/opendaq/device_type_factory.h
  core/opendaq/device/include/opendaq/device_type_impl.h
  core/opendaq/device/src/device_type_impl.cpp
  core/opendaq/signal/include/opendaq/input_port_impl.h
  core/opendaq/signal/tests/test_data_path.cpp
  core/opendaq/signal/tests/test_input_port.cpp
  core/opendaq/signal/tests/test_packet_e2e.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  regression/tests/reg_p_test_device.cpp
  regression/tests/reg_p_test_input_port.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_client_folder_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_client_input_port_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_server.h
  shared/libraries/config_protocol/include/config_protocol/config_server_device.h
  shared/libraries/config_protocol/include/config_protocol/config_server_input_port.h
  shared/libraries/config_protocol/src/config_protocol_client.cpp
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/config_protocol/tests/test_config_client_server.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
  shared/libraries/config_protocol/tests/test_utils.cpp
  shared/libraries/config_protocol/tests/test_utils.h
Labels: enhancement

#551 .NET Bindings - Generate `CoreTypesDllInfo.cs` automatically in pre-build step
  bindings/dotnet/CMakeLists.txt
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/CoreTypesDllInfo.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/CoreTypesDllInfo.txt
Labels: enhancement, bindings:c#

#550 Inject openDAQ version from a single file
  .github/workflows/build_antora_docs.yml
  .github/workflows/check_version.yml
  .github/workflows/deploy.yml
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
  bindings/dotnet/openDAQ.Net/openDAQDemo.Net/openDAQDemo.Net.csproj
  changelog/changelog_3.0.0-4.0.0.txt
  core/CMakeLists.txt
  docs/Antora-specs/antora.yml
  docs/Antora/antora.yml
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_cpp.adoc
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
  docs/version_injector.py
  examples/CMakeLists.txt
  examples/cpp/CMakeLists.txt
  modules/audio_device_module/CMakeLists.txt
  modules/empty_module/CMakeLists.txt
  modules/native_streaming_client_module/CMakeLists.txt
  modules/native_streaming_server_module/CMakeLists.txt
  modules/opcua_client_module/CMakeLists.txt
  modules/opcua_server_module/CMakeLists.txt
  modules/ref_device_module/CMakeLists.txt
  modules/ref_fb_module/CMakeLists.txt
  modules/websocket_streaming_client_module/CMakeLists.txt
  modules/websocket_streaming_server_module/CMakeLists.txt
  opendaq_version
  shared/libraries/opcuatms/opcuatms/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_client/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_server/CMakeLists.txt
Labels: documentation, enhancement, ci, bindings:c#

#552 Transform changelogs into markdown (`.md`) files
  changelog/changelog_1.0.0-2.0.0.md
  changelog/changelog_2.0.0-3.0.0.md
  changelog/changelog_3.0.0-4.0.0.md
  external/CMakeLists.txt
Labels: enhancement

#553 <TBBAS-1842> Remove redundant properties from native streaming config
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_default_config.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
Labels: bug

#549 TBBAS-1780, TBBAS-1794 MultiReader timeout fixes
  core/opendaq/reader/include/opendaq/read_info.h
  core/opendaq/reader/src/multi_reader_impl.cpp
  core/opendaq/reader/tests/test_multi_reader.cpp
Labels: bug

#554 openDAQ versioning fixes
  docs/Antora-specs/antora.yml
  docs/Antora/antora.yml
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_cpp.adoc
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_aligned_signals.adoc
  docs/version_injector.py
Labels: documentation

#557 Update bug report form to include programming language and change `howto.adoc` order so it's the same across the board
  .github/ISSUE_TEMPLATE/1-BUG-REPORT.yml
  docs/Antora/modules/howto_guides/pages/howto.adoc
Labels: documentation

#544 Implement LogFileInfo interface
  bindings/python/opendaq/CMakeLists.txt
  bindings/python/opendaq/generated/device/py_device.cpp
  bindings/python/opendaq/generated/device/py_log_file_info.cpp
  bindings/python/opendaq/generated/device/py_log_file_info_builder.cpp
  bindings/python/opendaq/generated/reader/py_multi_reader_builder.cpp
  bindings/python/opendaq/include/py_opendaq/py_opendaq.h
  bindings/python/opendaq/py_opendaq.cpp
  bindings/python/run_rtgen.sh
  changelog/changelog_3.0.0-4.0.0.md
  core/opendaq/device/include/opendaq/address_info.h
  core/opendaq/device/include/opendaq/device.h
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/include/opendaq/log_file_info.h
  core/opendaq/device/include/opendaq/log_file_info_builder.h
  core/opendaq/device/include/opendaq/log_file_info_builder_impl.h
  core/opendaq/device/include/opendaq/log_file_info_factory.h
  core/opendaq/device/include/opendaq/log_file_info_impl.h
  core/opendaq/device/src/CMakeLists.txt
  core/opendaq/device/src/log_file_info_builder_impl.cpp
  core/opendaq/device/src/log_file_info_impl.cpp
  core/opendaq/device/tests/CMakeLists.txt
  core/opendaq/device/tests/test_log_file_info.cpp
  core/opendaq/opendaq/include/opendaq/instance_builder_impl.h
  core/opendaq/opendaq/include/opendaq/instance_impl.h
  core/opendaq/opendaq/include/opendaq/opendaq.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/device.h
  core/opendaq/opendaq/src/instance_builder_impl.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
  examples/cpp/quick_start/quick_start_simulator.cpp
  modules/ref_device_module/include/ref_device_module/ref_device_impl.h
  modules/ref_device_module/src/ref_device_impl.cpp
  modules/ref_device_module/tests/test_ref_device_module.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_server_device.h
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_device_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
Labels: enhancement

#563 Fix multi reader example
  examples/cpp/multi_reader_example/multi_reader_example.cpp
Labels: bug

#566 Fix sprintf error on make error info with percentage in text
  core/coretypes/include/coretypes/ctutils.h
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
Labels: bug

#556 [TBBAS-1850]: Implement communication protocol version info
  bindings/python/opendaq/generated/device/py_server_capability.cpp
  changelog/changelog_3.0.0-4.0.0.md
  core/opendaq/device/include/opendaq/server_capability.h
  core/opendaq/device/include/opendaq/server_capability_config.h
  core/opendaq/device/include/opendaq/server_capability_impl.h
  core/opendaq/device/src/device_info_impl.cpp
  core/opendaq/device/src/server_capability_impl.cpp
  core/opendaq/modulemanager/src/mdns_discovery_server_impl.cpp
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
  modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
  modules/opcua_client_module/src/opcua_client_module_impl.cpp
  modules/opcua_server_module/src/opcua_server_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
  modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
  modules/websocket_streaming_server_module/src/websocket_streaming_server_impl.cpp
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/tms_server.h
  shared/libraries/opcuatms/opcuatms_server/src/tms_server.cpp
Labels: bug, enhancement

#570 <TBBAS-1407> Add support for serialization of list properties on prop…
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/tests/test_property_object.cpp
Labels: bug

#568 Update quick_start_simulator to vbox simulator
  examples/cpp/quick_start/quick_start_simulator.cpp
  simulator/simulator_app/src/main.cpp
Labels: enhancement
