Repository openDAQ/openDAQ, pull requests merged in 2025-05, with the labels that each got.

#743 high-performance WebSocket streaming server
  changelog/changelog_3.10-3.20.md
  external/CMakeLists.txt
  external/nlohmann_json/CMakeLists.txt
  external/streaming_protocol/CMakeLists.txt
  modules/CMakeLists.txt
  modules/new_websocket_streaming_server_module/CMakeLists.txt
  modules/new_websocket_streaming_server_module/docs/index.md
  modules/new_websocket_streaming_server_module/include/base64/base64.hpp
  modules/new_websocket_streaming_server_module/include/httpparser/httprequestparser.h
  modules/new_websocket_streaming_server_module/include/httpparser/httpresponseparser.h
  modules/new_websocket_streaming_server_module/include/httpparser/request.h
  modules/new_websocket_streaming_server_module/include/httpparser/response.h
  modules/new_websocket_streaming_server_module/include/httpparser/urlparser.h
  modules/new_websocket_streaming_server_module/include/new_websocket_streaming_server_module/common.h
  modules/new_websocket_streaming_server_module/include/new_websocket_streaming_server_module/module_dll.h
  modules/new_websocket_streaming_server_module/include/new_websocket_streaming_server_module/new_websocket_streaming_server_impl.h
  modules/new_websocket_streaming_server_module/include/new_websocket_streaming_server_module/new_websocket_streaming_server_module_impl.h
  modules/new_websocket_streaming_server_module/include/streaming/constant_signal_writer.hpp
  modules/new_websocket_streaming_server_module/include/streaming/explicit_signal_writer.hpp
  modules/new_websocket_streaming_server_module/include/streaming/httpparser_utils.hpp
  modules/new_websocket_streaming_server_module/include/streaming/linear_signal_writer.hpp
  modules/new_websocket_streaming_server_module/include/streaming/metadata.hpp
  modules/new_websocket_streaming_server_module/include/streaming/signal_writer.hpp
  modules/new_websocket_streaming_server_module/include/streaming/signal_writer_factory.hpp
  modules/new_websocket_streaming_server_module/include/streaming/streaming_protocol.hpp
  modules/new_websocket_streaming_server_module/include/streaming/subscribed_client.hpp
  modules/new_websocket_streaming_server_module/include/streaming/websocket_client.hpp
  modules/new_websocket_streaming_server_module/include/streaming/websocket_client_established.hpp
  modules/new_websocket_streaming_server_module/include/streaming/websocket_client_negotiating.hpp
  modules/new_websocket_streaming_server_module/include/streaming/websocket_protocol.hpp
  modules/new_websocket_streaming_server_module/include/streaming/websocket_server.dox
  modules/new_websocket_streaming_server_module/include/streaming/websocket_server.hpp
  modules/new_websocket_streaming_server_module/include/streaming/websocket_signal_listener_impl.hpp
  modules/new_websocket_streaming_server_module/src/CMakeLists.txt
  modules/new_websocket_streaming_server_module/src/metadata.cpp
  modules/new_websocket_streaming_server_module/src/module_dll.cpp
  modules/new_websocket_streaming_server_module/src/new_websocket_streaming_server_impl.cpp
  modules/new_websocket_streaming_server_module/src/new_websocket_streaming_server_module_impl.cpp
  modules/new_websocket_streaming_server_module/src/signal_writer_factory.cpp
  modules/new_websocket_streaming_server_module/src/websocket_client_established.cpp
  modules/new_websocket_streaming_server_module/src/websocket_client_negotiating.cpp
  modules/new_websocket_streaming_server_module/src/websocket_protocol.cpp
  modules/new_websocket_streaming_server_module/src/websocket_server.cpp
  modules/new_websocket_streaming_server_module/src/websocket_signal_listener_impl.cpp
  modules/new_websocket_streaming_server_module/tests/CMakeLists.txt
  modules/new_websocket_streaming_server_module/tests/test_app.cpp
  modules/new_websocket_streaming_server_module/tests/test_new_websocket_streaming_server_module.cpp
  modules/ref_device_module/src/ref_can_channel_impl.cpp
  modules/ref_device_module/src/ref_channel_impl.cpp
  shared/libraries/websocket_streaming/include/websocket_streaming/input_signal.h
  shared/libraries/websocket_streaming/include/websocket_streaming/signal_descriptor_converter.h
  shared/libraries/websocket_streaming/include/websocket_streaming/streaming_client.h
  shared/libraries/websocket_streaming/src/input_signal.cpp
  shared/libraries/websocket_streaming/src/signal_descriptor_converter.cpp
  shared/libraries/websocket_streaming/src/streaming_client.cpp
  shared/libraries/websocket_streaming/tests/test_signal_descriptor_converter.cpp
  shared/tools/license-header-checker/ignore-filter.txt
Labels: enhancement

#785 Remove Boost::endian dep
  modules/new_websocket_streaming_server_module/src/CMakeLists.txt
Labels: bug

#787 bump release candidate to 3.19.3rc
  opendaq_version
Labels: ci

#788 Component property search
  bindings/python/core_objects/CMakeLists.txt
  bindings/python/core_objects/generated/py_property_filter.cpp
  bindings/python/core_objects/generated/py_property_object.cpp
  bindings/python/core_objects/include/py_core_objects/py_core_objects.h
  bindings/python/core_objects/py_core_objects.cpp
  bindings/python/opendaq/generated/component/py_component.cpp
  bindings/python/run_rtgen.sh
  changelog/changelog_3.10-3.20.md
  core/coreobjects/include/coreobjects/property_filter.h
  core/coreobjects/include/coreobjects/property_filter_factory.h
  core/coreobjects/include/coreobjects/property_filter_impl.h
  core/coreobjects/include/coreobjects/property_object.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/src/CMakeLists.txt
  core/coreobjects/src/property_filter_impl.cpp
  core/coreobjects/tests/CMakeLists.txt
  core/coreobjects/tests/test_property_search.cpp
  core/coretypes/include/coretypes/recursive_search.h
  core/coretypes/include/coretypes/recursive_search_ptr.h
  core/coretypes/src/CMakeLists.txt
  core/opendaq/component/include/opendaq/component.h
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/include/opendaq/search_filter_impl.h
  core/opendaq/component/src/CMakeLists.txt
  core/opendaq/component/src/search_filter_impl.cpp
  core/opendaq/device/tests/test_tree_traversal.cpp
  core/opendaq/opendaq/include/opendaq/instance_impl.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/component.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/signal.h
  core/opendaq/opendaq/src/instance_impl.cpp
Labels: enhancement

#790 Fix input port to signal notification
  changelog/changelog_3.10-3.20.md
  core/opendaq/signal/include/opendaq/input_port_impl.h
  core/opendaq/signal/tests/test_input_port.cpp
  shared/libraries/config_protocol/tests/test_c2d_streaming.cpp
Labels: bug

#794 Refactor child object cloning + thread safety
  changelog/changelog_3.10-3.20.md
  core/coreobjects/include/coreobjects/property_builder_impl.h
  core/coreobjects/include/coreobjects/property_impl.h
  core/coreobjects/include/coreobjects/property_object_impl.h
Labels: bug

#795 Move return macros to cutils.h
  core/coretypes/include/coretypes/ctutils.h
  core/coretypes/include/coretypes/validation.h
Labels: bug

#789 Optimize Signal Packet Handling by Deferring Last Value Calculation
  changelog/changelog_3.10-3.20.md
  core/opendaq/opendaq/src/instance_impl.cpp
  core/opendaq/signal/include/opendaq/binary_data_packet_impl.h
  core/opendaq/signal/include/opendaq/data_descriptor_impl.h
  core/opendaq/signal/include/opendaq/data_packet.h
  core/opendaq/signal/include/opendaq/data_packet_impl.h
  core/opendaq/signal/include/opendaq/data_rule_calc.h
  core/opendaq/signal/include/opendaq/data_rule_calc_private.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/signal/src/data_descriptor_impl.cpp
  core/opendaq/signal/tests/test_signal.cpp
Labels: enhancement

#799 Implementing missed unequal operators for the object ptr
  core/coretypes/include/coretypes/objectptr.h
Labels: bug

#803 Fix new LT and csv module install
  cmake/Packing.cmake
Labels: bug

#805 Fix Antora notes
  docs/Antora/modules/explanations/pages/components.adoc
  docs/Antora/modules/explanations/pages/device.adoc
  docs/Antora/modules/explanations/pages/interfaces_objects_wrappers.adoc
  docs/Antora/modules/explanations/pages/multireader_spec.adoc
  docs/Antora/modules/explanations/pages/property_system.adoc
  docs/Antora/modules/explanations/pages/protocol_features_characteristics.adoc
  docs/Antora/modules/howto_guides/pages/howto_access_control_introduction.adoc
  docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
  docs/Antora/modules/tutorials/pages/quick_start_building_opendaq.adoc
  docs/Antora/modules/tutorials/pages/quick_start_setting_up_cpp.adoc
  docs/Antora/modules/tutorials/pages/quick_start_setting_up_csharp.adoc
  docs/Antora/modules/tutorials/pages/tutorial_application.adoc
Labels: documentation

#807 Device operation mode switching in Python GUI Demo Application
  bindings/python/opendaq/generated/device/py_device.cpp
  changelog/changelog_3.20-3.30.md
  examples/python/gui_demo/components/block_view.py
Labels: enhancement, bindings:python

#806 Fix hidden components deserialization
  changelog/changelog_3.10-3.20.md
  core/opendaq/opendaq/mocks/advanced_components_setup_utils.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
  shared/libraries/config_protocol/src/config_protocol_client.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
Labels: bug

#812 Fix Incorrect SDK Version Display for Devices with SDK <3.10.3
  shared/libraries/discovery/src/daq_discovery_client.cpp
Labels: bug

#810 Load individual modules
  bindings/python/opendaq/generated/modulemanager/py_module_manager.cpp
  changelog/changelog_3.20-3.30.md
  core/opendaq/modulemanager/include/opendaq/module_library.h
  core/opendaq/modulemanager/include/opendaq/module_manager.h
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/modulemanager/tests/CMakeLists.txt
  core/opendaq/modulemanager/tests/test_module_manager_internals.cpp
  docs/tests/test_modules.cpp
  examples/python/gui_demo.py
Labels: enhancement

#821 Fix CPP 20 and 23 compatibility issues
  bindings/python/py_opendaq_daq/CMakeLists.txt
  changelog/changelog_3.10-3.20.md
  core/coreobjects/tests/test_evalvalue.cpp
  core/coretypes/include/coretypes/bb_exception.h
  core/coretypes/include/coretypes/function_custom_impl.h
  core/coretypes/include/coretypes/function_impl.h
  core/coretypes/include/coretypes/procedure_custom_impl.h
  core/coretypes/src/json_serializer_impl.cpp
  core/opendaq/logger/tests/test_logger_sink.cpp
  core/opendaq/opendaq/mocks/include/opendaq/gmock/context.h
  core/opendaq/scheduler/src/awaitable_impl.cpp
  core/opendaq/signal/include/opendaq/binary_data_packet_impl.h
  external/bcrypt/tests/test_bcrypt.cpp
  external/rapidjson/include/rapidjson/document.h
Labels: bug

#823 Ensure property order is preserved from server to client via the native protocol
  changelog/changelog_3.10-3.20.md
  core/corecontainers/include/coretypes/listptr.h
  core/coreobjects/include/coreobjects/core_event_args.h
  core/coreobjects/include/coreobjects/core_event_args_factory.h
  core/coreobjects/include/coreobjects/core_event_args_ids.h
  core/coreobjects/include/coreobjects/core_event_args_impl.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/src/core_event_args_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/src/config_protocol_server.cpp
Labels: bug

#791 [TBBAS-2183/SHS-152] .NET Bindings - Fixed AccessViolation on Garbage Collection
  bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/OpenDAQ_CITests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coretypes/BaseObject.cs
Labels: bug, enhancement, bindings:c#
