Repository openDAQ/openDAQ, pull requests merged in 2025-06, with the labels that each got.

#832 Revert faulty LT changes
  external/streaming_protocol/CMakeLists.txt
Labels: bug

#829 Add Antora search
  .github/workflows/build_antora_docs.yml
  .github/workflows/deploy.yml
  antora-playbook-dev.yml
  antora-playbook.yml
  changelog/changelog_3.20-3.30.md
Labels: documentation, enhancement

#826 Add GIL-safe queued Python event handling to prevent deadlocks in pybind11 callbacks
  bindings/python/core_types/CMakeLists.txt
  bindings/python/core_types/include/py_core_types/py_core_types.h
  bindings/python/core_types/include/py_core_types/py_event_handler_impl.h
  bindings/python/core_types/include/py_core_types/py_event_queue.h
  bindings/python/core_types/include/py_core_types/py_opendaq_daq.h
  bindings/python/core_types/include/py_core_types/py_queued_event_handler.h
  bindings/python/core_types/include/py_core_types/py_queued_event_handler_impl.h
  bindings/python/core_types/src/py_core_types.cpp
  bindings/python/core_types/src/py_event_queue.cpp
  bindings/python/core_types/src/py_queued_event_handler_impl.cpp
  bindings/python/package/opendaq/__init__.py
  bindings/python/py_opendaq_daq/CMakeLists.txt
  bindings/python/py_opendaq_daq/src/opendaq_daq.cpp
  bindings/python/tests/opendaq_test.py
  bindings/python/tests/test_core_type_string.py
  bindings/python/tests/test_property_system.py
  core/coretypes/include/coretypes/objectptr.h
  core/opendaq/opendaq/include/opendaq/instance_builder_impl.h
  core/opendaq/opendaq/src/instance_impl.cpp
  examples/python/gui_demo.py
  examples/python/gui_demo/app_context.py
  examples/python/gui_demo/components/function_dialog.py
Labels: bug, bindings:python

#833 Fix Invalid MultiReader in PowerReaderFb on Sample Rate Change
  changelog/changelog_3.10-3.20.md
  core/opendaq/reader/src/multi_reader_impl.cpp
  modules/ref_fb_module/src/power_reader_fb_impl.cpp
Labels: bug

#817 Increase cmake min version to 3.10 to reduce warning while configuration
  core/coreobjects/CMakeLists.txt
  core/coretypes/CMakeLists.txt
  external/opcua_daq_types/CMakeLists.txt
  modules/audio_device_module/CMakeLists.txt
  modules/basic_csv_recorder_module/CMakeLists.txt
  modules/empty_module/CMakeLists.txt
  modules/native_streaming_client_module/CMakeLists.txt
  modules/native_streaming_server_module/CMakeLists.txt
  modules/new_websocket_streaming_server_module/CMakeLists.txt
  modules/opcua_client_module/CMakeLists.txt
  modules/opcua_server_module/CMakeLists.txt
  modules/ref_device_module/CMakeLists.txt
  modules/ref_fb_module/CMakeLists.txt
  modules/websocket_streaming_client_module/CMakeLists.txt
  modules/websocket_streaming_server_module/CMakeLists.txt
  shared/libraries/discovery/CMakeLists.txt
  shared/libraries/discovery_common/CMakeLists.txt
  shared/libraries/discovery_server/CMakeLists.txt
  shared/libraries/native_streaming_protocol/CMakeLists.txt
  shared/libraries/opcua/opcuaclient/CMakeLists.txt
  shared/libraries/opcua/opcuaserver/CMakeLists.txt
  shared/libraries/opcua/opcuashared/CMakeLists.txt
  shared/libraries/opcua/tests/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_client/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_server/CMakeLists.txt
  shared/libraries/opcuatms/tests/CMakeLists.txt
  shared/libraries/packet_streaming/CMakeLists.txt
  shared/libraries/testutils/CMakeLists.txt
  shared/libraries/utils/CMakeLists.txt
  shared/libraries/websocket_streaming/CMakeLists.txt
  simulator/simulator_app/CMakeLists.txt
Labels: enhancement

#835 Remove opendaq_dev library
  changelog/changelog_3.20-3.30.md
  cmake/DaqComponents.cmake
  cmake/DaqInternal.cmake
  core/opendaq/CMakeLists.txt
  core/opendaq/device/include/opendaq/server_capability_impl.h
  core/opendaq/device/src/server_capability_impl.cpp
  core/opendaq/modulemanager/tests/CMakeLists.txt
  core/opendaq/opendaq/include/opendaq/client_type.h
  core/opendaq/opendaq/src/client_type.cpp
  core/opendaq/scheduler/include/opendaq/scheduler_impl.h
  core/opendaq/scheduler/src/scheduler_impl.cpp
  core/opendaq/scheduler/tests/CMakeLists.txt
  core/opendaq/scheduler/tests/test_scheduler_internals.cpp
  core/opendaq/utility/tests/CMakeLists.txt
  shared/libraries/native_streaming_protocol/src/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_client/src/CMakeLists.txt
Labels: enhancement

#842 Exclude ComponentConfig from OPC UA Component Properties
  changelog/changelog_3.10-3.20.md
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_component_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
  shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/objects/tms_server_component.h
Labels: bug, OPC UA

#828 Parallel device connection
  bindings/c/include/copendaq/device/device.h
  bindings/c/include/copendaq/modulemanager/module_manager_utils.h
  bindings/c/src/copendaq/device/device.cpp
  bindings/c/src/copendaq/modulemanager/module_manager_utils.cpp
  bindings/python/opendaq/generated/device/py_device.cpp
  changelog/changelog_3.20-3.30.md
  core/coretypes/include/coretypes/errorinfo_impl.h
  core/coretypes/include/coretypes/errors.h
  core/coretypes/src/errorinfo_impl.cpp
  core/coretypes/tests/test_errorinfo.cpp
  core/opendaq/device/include/opendaq/device.h
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/tests/test_device.cpp
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/include/opendaq/module_manager_utils.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/modulemanager/tests/module_manager_test.cpp
  core/opendaq/opendaq/include/opendaq/instance_impl.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/device.h
  core/opendaq/opendaq/mocks/include/opendaq/mock/advanced_components_setup_utils.h
  core/opendaq/opendaq/src/instance_impl.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_server_device.h
  shared/libraries/config_protocol/src/config_protocol_client.cpp
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_access_control.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_device_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
Labels: enhancement

#848 Gracefully handle operation mode getters when not supported on server
  changelog/changelog_3.20-3.30.md
  core/coreobjects/include/coreobjects/eval_nodes.h
  shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
Labels: bug
