Repository openDAQ/openDAQ, pull requests merged in 2025-03, with the labels that each got.

#719 Fix selection value dot access
  changelog/changelog_3.10-3.20.md
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/tests/test_property_object.cpp
  core/opendaq/scheduler/tests/test_task_internals.cpp
  shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
  shared/libraries/config_protocol/tests/test_utils.cpp
  shared/libraries/opcua/opcuaclient/tests/src/test_opcuaasyncexecthread.cpp
Labels: bug

#720 Other/native streaming perf optimization stage 2
  changelog/changelog_3.10-3.20.md
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/native_streaming_server_module/include/native_streaming_server_module/native_streaming_server_impl.h
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
  modules/native_streaming_server_module/tests/test_native_streaming_server_module.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_streaming_producer.h
  shared/libraries/config_protocol/src/config_protocol_streaming_producer.cpp
  shared/libraries/config_protocol/tests/test_c2d_streaming.cpp
  shared/libraries/config_protocol/tests/test_config_client_server.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_access_control.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_device_locking.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_view_only_client.cpp
  shared/libraries/config_protocol/tests/test_core_events.cpp
  shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
  shared/libraries/config_protocol/tests/test_ref_modules.cpp
  shared/libraries/config_protocol/tests/test_remote_update.cpp
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_client_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h
  shared/libraries/native_streaming_protocol/src/base_session_handler.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
  shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
  shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
  shared/libraries/packet_streaming/include/packet_streaming/packet_streaming.h
  shared/libraries/packet_streaming/include/packet_streaming/packet_streaming_server.h
  shared/libraries/packet_streaming/src/packet_streaming.cpp
  shared/libraries/packet_streaming/src/packet_streaming_server.cpp
  shared/libraries/packet_streaming/tests/test_packet_streaming.cpp
Labels: enhancement

#724 Fixing object ref count in python
  core/coreobjects/include/coreobjects/permissions_builder_impl.h
  core/coreobjects/include/coreobjects/permissions_impl.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/src/permissions_builder_impl.cpp
  core/coreobjects/src/permissions_impl.cpp
  core/opendaq/component/include/opendaq/component_impl.h
Labels: bug

#718 Add RPCs for handling nested function blocks
  changelog/changelog_3.10-3.20.md
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_function_block_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_server_component.h
  shared/libraries/config_protocol/include/config_protocol/config_server_device.h
  shared/libraries/config_protocol/src/config_protocol_client.cpp
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
  shared/libraries/config_protocol/tests/test_utils.cpp
  shared/libraries/config_protocol/tests/test_utils.h
Labels: enhancement

#727 .NET Bindings - Fix loading `libopendaq-64-3.so` in Linux
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/opendaq/OpenDAQFactory.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net/opendaq.cd
  bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmMain.cs
Labels: bug, bindings:c#

#729 Python GUI app: attributes dialog, changeable device info, metadata fields fix
  changelog/changelog_3.10-3.20.md
  examples/python/gui_demo/components/attributes_dialog.py
  examples/python/gui_demo/components/data_descriptor_treeview.py
  examples/python/gui_demo/components/device_info_dialog.py
  examples/python/gui_demo/components/generic_attributes_treeview.py
  examples/python/gui_demo/components/input_port_row_view.py
  examples/python/gui_demo/components/metadata_fields_selector_dialog.py
Labels: bug, enhancement, bindings:python

#728 Add scan timeout in `createDevice`
  changelog/changelog_3.10-3.20.md
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/modulemanager/tests/module_manager_test.cpp
  core/opendaq/opendaq/src/instance_builder_impl.cpp
Labels: enhancement

#732 Fix compiling issue because of __VA_ARGS__ in macros DAQ_THROW_EXCEPTION
  core/coretypes/include/coretypes/exceptions.h
Labels: bug

#731 Nested property object cleanup
  CMakeBasePresets.json
  changelog/changelog_3.10-3.20.md
  core/coreobjects/include/coreobjects/property.h
  core/coreobjects/include/coreobjects/property_impl.h
  core/coreobjects/include/coreobjects/property_internal.h
  core/coreobjects/include/coreobjects/property_object.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/src/property_object_class_builder_impl.cpp
  core/coreobjects/tests/test_property_object.cpp
  core/coreobjects/tests/test_property_object_update.cpp
  core/opendaq/opendaq/mocks/CMakeLists.txt
  core/opendaq/opendaq/mocks/advanced_components_setup_utils.cpp
  core/opendaq/opendaq/mocks/include/opendaq/mock/advanced_components_setup_utils.h
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_server_component.h
  shared/libraries/config_protocol/src/config_protocol_client.cpp
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/config_protocol/tests/CMakeLists.txt
  shared/libraries/config_protocol/tests/test_c2d_streaming.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_access_control.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_device_locking.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
  shared/libraries/config_protocol/tests/test_config_protocol_view_only_client.cpp
  shared/libraries/config_protocol/tests/test_core_events.cpp
  shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
  shared/libraries/config_protocol/tests/test_remote_update.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_property_object_impl.h
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_sync_component_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_integration.cpp
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_property_object.cpp
Labels: bug, enhancement

#733 Add element IntfID to list/dict serialization + Serialization versioning
  changelog/changelog_3.10-3.20.md
  core/corecontainers/include/coretypes/listobject_impl.h
  core/corecontainers/src/dictobject_impl.cpp
  core/corecontainers/src/listobject_impl.cpp
  core/coreobjects/src/user_impl.cpp
  core/coreobjects/tests/test_property.cpp
  core/coreobjects/tests/test_property_object_class.cpp
  core/coretypes/include/coretypes/common.h
  core/coretypes/include/coretypes/json_serializer.h
  core/coretypes/include/coretypes/json_serializer_factory.h
  core/coretypes/include/coretypes/json_serializer_impl.h
  core/coretypes/include/coretypes/serializer.h
  core/coretypes/include/coretypes/serializer_ptr.h
  core/coretypes/src/json_serializer_impl.cpp
  core/coretypes/src/util.cpp
  core/coretypes/tests/test_dictobject.cpp
  core/coretypes/tests/test_intfid.cpp
  core/coretypes/tests/test_json_serializer.cpp
  core/coretypes/tests/test_listobject.cpp
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/src/config_protocol_client.cpp
Labels: bug

#725 Optimize Native Streaming server packet reading
  changelog/changelog_3.10-3.20.md
  core/opendaq/reader/src/packet_reader_impl.cpp
  core/opendaq/reader/tests/test_packet_reader.cpp
  core/opendaq/scheduler/tests/test_task_internals.cpp
  core/opendaq/signal/include/opendaq/connection_impl.h
  core/opendaq/signal/include/opendaq/connection_internal.h
  core/opendaq/signal/src/connection_impl.cpp
  core/opendaq/signal/tests/test_connection.cpp
  modules/native_streaming_server_module/include/native_streaming_server_module/native_streaming_server_impl.h
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
  modules/tests/test_opendaq_device_modules/test_streaming.cpp
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
  shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
  shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
Labels: enhancement

#740 [TBBAS-2157] Function blocks with dynamic input ports don't get correctly loaded if input port names don't match name
  changelog/changelog_3.10-3.20.md
  core/opendaq/functionblock/include/opendaq/function_block_impl.h
Labels: bug

#738 Set default value as args newValue on clear instead of empty ptr
  changelog/changelog_3.10-3.20.md
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/tests/test_property_object.cpp
Labels: enhancement
