Repository openDAQ/openDAQ, pull requests merged in 2025-01, with the labels that each got.

#660 Serialize component name when equal to localID
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/tests/test_component.cpp
  modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
Labels: bug

#650 Component status fixes
  .github/pull_request_template.md
  README.md
  changelog/changelog_1.0.0-2.0.0.md
  changelog/changelog_2.0.0-3.0.0.md
  changelog/changelog_3.0.0-4.0.0.md
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/include/opendaq/component_status_container_impl.h
  core/opendaq/component/tests/test_component.cpp
  modules/ref_fb_module/include/ref_fb_module/renderer_fb_impl.h
  modules/ref_fb_module/src/classifier_fb_impl.cpp
  modules/ref_fb_module/src/fft_fb_impl.cpp
  modules/ref_fb_module/src/power_fb_impl.cpp
  modules/ref_fb_module/src/power_reader_fb_impl.cpp
  modules/ref_fb_module/src/renderer_fb_impl.cpp
  modules/ref_fb_module/src/scaling_fb_impl.cpp
  modules/ref_fb_module/src/statistics_fb_impl.cpp
  modules/ref_fb_module/src/struct_decoder_fb_impl.cpp
  modules/ref_fb_module/src/trigger_fb_impl.cpp
  modules/ref_fb_module/tests/test_fb_power_reader.cpp
  modules/ref_fb_module/tests/test_fb_statistics.cpp
  modules/ref_fb_module/tests/test_fb_trigger.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  modules/tests/test_ref_modules/test_ref_modules.cpp
Labels: bug

#659 [TBBAS-2001] openDAQ module loading fails on Android
  core/opendaq/component/src/CMakeLists.txt
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  modules/ref_device_module/src/ref_device_impl.cpp
Labels: bug

#662 Use generic Property Treeview in Python GUI Demo Application
  examples/python/gui_demo/components/add_config_dialog.py
  examples/python/gui_demo/components/add_device_dialog.py
  examples/python/gui_demo/components/block_view.py
  examples/python/gui_demo/components/generic_properties_treeview.py
  examples/python/gui_demo/components/load_instance_config_dialog.py
  examples/python/gui_demo/components/properties_view.py
  examples/python/gui_demo/utils.py
Labels: enhancement, bindings:python

#667 [TBBAS-2050] .NET Bindings - Bump-up to .NET 8.0
  bindings/dotnet/openDAQ.Net/README.md
  bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/openDAQ.Net.CI.Test.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net.NuGet.Test/openDAQ.Net.NuGet.Test.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/openDAQ.Net.Test.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coretypes/OpenDaqException.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/media/README.md
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
Labels: enhancement, bindings:c#

#663 Add disconnection/reconnection detection examples
  examples/CMakeLists.txt
  examples/cpp/CMakeLists.txt
  examples/cpp/reconnection_example/CMakeLists.txt
  examples/cpp/reconnection_example/reconnection.cpp
  examples/cpp/reconnection_example/reconnection_v3_10.cpp
Labels: documentation

#665 Other/simulator ip modification
  .github/workflows/package.yml
  bindings/python/opendaq/include/py_opendaq/py_typed_reader.h
  core/opendaq/modulemanager/src/mdns_discovery_server_impl.cpp
  core/opendaq/opendaq/mocks/mock_physical_device.cpp
  examples/CMakeLists.txt
  examples/cpp/CMakeLists.txt
  examples/cpp/ip_modification/CMakeLists.txt
  examples/cpp/ip_modification/ip_modification.cpp
  examples/python/ip_modification.py
  modules/CMakeLists.txt
  modules/ref_device_module/include/ref_device_module/ref_device_impl.h
  modules/ref_device_module/src/ref_device_impl.cpp
  modules/tests/test_opendaq_device_modules/test_default_config.cpp
  shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
  shared/libraries/discovery_common/include/discovery_common/daq_discovery_common.h
  shared/libraries/discovery_common/src/daq_discovery_common.cpp
  simulator/CMakeLists.txt
  simulator/Vagrantfile
  simulator/configurator.py
  simulator/netplan_manager.py
  simulator/opcuatms.service
  simulator/opendaq-config.json
  simulator/simulator.service
  simulator/simulator_app/src/main.cpp
Labels: enhancement

#673 Initialize `futureComponentStatus` and `futureComponentMessage` in `renderer_fb_impl.cpp`, thereby preventing unwarranted crashes
  modules/ref_fb_module/src/renderer_fb_impl.cpp
Labels: bug

#666 [TBBAS-1994][TBBAS-2060] Clean up exceptions in GUI App and Multireader example
  examples/python/gui_demo.py
  examples/python/gui_demo/components/add_device_dialog.py
  examples/python/gui_demo/utils.py
  examples/python/guide/how_to_multiread.py
Labels: bug, bindings:python

#671 Apply `run_rtgen.sh`
  bindings/python/core_objects/generated/py_property_object.cpp
  bindings/python/core_types/generated/py_simple_type.cpp
  bindings/python/core_types/generated/py_struct_builder.cpp
  bindings/python/core_types/generated/py_struct_type.cpp
  bindings/python/core_types/generated/py_type.cpp
  bindings/python/opendaq/generated/component/py_component_status_container.cpp
  bindings/python/opendaq/generated/component/py_component_status_container_private.cpp
  bindings/python/opendaq/generated/functionblock/py_function_block.cpp
  bindings/python/opendaq/generated/reader/py_multi_reader_builder.cpp
Labels: bindings:python

#675 Add Python app option to load additional module paths.
  examples/python/gui_demo.py
  examples/python/gui_demo/app_context.py
Labels: enhancement

#676 Fix getPropertySelectionValue was returning the old value
  core/coreobjects/include/coreobjects/property_object_impl.h
  shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
Labels: bug

#684 Allow for conversion between development and release version
  docs/Antora-specs/antora.yml
  docs/Antora/antora.yml
  opendaq_version_bump.py
Labels: enhancement

#679 Fix getPropertySelectionValue was returning the old value on main
  core/coreobjects/include/coreobjects/property_object_impl.h
  shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
Labels: bug

#681 Structs example added
  examples/python/struct_properties.py
Labels: documentation, bindings:python

#685 Fix/reconnect exclusive client
  modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
Labels: bug

#683 fix test ServerCoreEvents failing with segfault on msvc 2017
  modules/native_streaming_client_module/src/native_device_impl.cpp
  shared/libraries/opcua/opcuaclient/src/opcuaclient.cpp
Labels: bug
