Repository openDAQ/openDAQ, pull requests merged in 2025-04, with the labels that each got.

#746 Bugfix: Initialize IProcedure objects to nullptr
  core/coretypes/include/coretypes/procedure_impl.h
Labels: bug

#756 Replaced WORKING_DIRECTORY by full path for all tests (RC 3.20 branch)
  core/coreobjects/tests/CMakeLists.txt
  core/coretypes/tests/CMakeLists.txt
  core/opendaq/component/tests/CMakeLists.txt
  core/opendaq/context/tests/CMakeLists.txt
  core/opendaq/device/tests/CMakeLists.txt
  core/opendaq/functionblock/tests/CMakeLists.txt
  core/opendaq/logger/tests/CMakeLists.txt
  core/opendaq/modulemanager/tests/CMakeLists.txt
  core/opendaq/opendaq/tests/CMakeLists.txt
  core/opendaq/reader/tests/CMakeLists.txt
  core/opendaq/scheduler/tests/CMakeLists.txt
  core/opendaq/server/tests/CMakeLists.txt
  core/opendaq/signal/tests/CMakeLists.txt
  core/opendaq/streaming/tests/CMakeLists.txt
  core/opendaq/synchronization/tests/CMakeLists.txt
  core/opendaq/utility/tests/CMakeLists.txt
  docs/tests/CMakeLists.txt
  external/bcrypt/tests/CMakeLists.txt
  modules/audio_device_module/tests/CMakeLists.txt
  modules/empty_module/tests/CMakeLists.txt
  modules/native_streaming_client_module/tests/CMakeLists.txt
  modules/native_streaming_server_module/tests/CMakeLists.txt
  modules/opcua_client_module/tests/CMakeLists.txt
  modules/opcua_server_module/tests/CMakeLists.txt
  modules/ref_device_module/tests/CMakeLists.txt
  modules/ref_fb_module/tests/CMakeLists.txt
  modules/tests/test_opendaq_device_modules/CMakeLists.txt
  modules/tests/test_ref_modules/CMakeLists.txt
  modules/websocket_streaming_client_module/tests/CMakeLists.txt
  modules/websocket_streaming_server_module/tests/CMakeLists.txt
  regression/tests/CMakeLists.txt
  shared/libraries/config_protocol/tests/CMakeLists.txt
  shared/libraries/native_streaming_protocol/tests/CMakeLists.txt
  shared/libraries/opcua/opcuaclient/tests/CMakeLists.txt
  shared/libraries/opcua/opcuaserver/tests/CMakeLists.txt
  shared/libraries/opcua/opcuashared/tests/CMakeLists.txt
  shared/libraries/opcua/tests/testopcua/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms/tests/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_client/tests/CMakeLists.txt
  shared/libraries/opcuatms/opcuatms_server/tests/CMakeLists.txt
  shared/libraries/opcuatms/tests/opcuatms_integration/CMakeLists.txt
  shared/libraries/packet_streaming/tests/CMakeLists.txt
  shared/libraries/utils/tests/CMakeLists.txt
  shared/libraries/websocket_streaming/tests/CMakeLists.txt
Labels: bug, ci

#751 Fix IPv6 addresses discovering on windows
  changelog/changelog_3.10-3.20.md
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/opcua_client_module/src/opcua_client_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
  modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
  shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
  shared/libraries/websocket_streaming/src/streaming_client.cpp
Labels: bug

#758 [TBBAS-1957] .NET bindings usage guide on Linux
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqGettingStartedGuidesTests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/openDAQ.Net.Test.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coreobjects/CoreObjectsFactory.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coretypes/CoreTypesFactory.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/opendaq/OpenDAQFactory.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
  docs/Antora/modules/getting_started/pages/quick_start_application.adoc
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_csharp.adoc
  examples/dotnet/quick_start/quick_start_simulator.cs
Labels: documentation, bindings:c#

#753 Fix reserved struct type deserialization
  changelog/changelog_3.10-3.20.md
  core/coretypes/include/coretypes/errors.h
  core/coretypes/include/coretypes/exceptions.h
  core/coretypes/src/struct_type_impl.cpp
  core/coretypes/src/type_manager_impl.cpp
  core/coretypes/tests/test_type_manager.cpp
Labels: bug

#761 Fix Antora versioning (3.20)
  docs/Antora-specs/antora.yml
  docs/Antora/antora.yml
Labels: bug, documentation

#763 Add missing items to changelog, move one item from features to bugs
  changelog/changelog_3.10-3.20.md
Labels: enhancement

#757 Merge discovery info and device info based on SN and manufacturer
  changelog/changelog_3.10-3.20.md
  core/opendaq/device/include/opendaq/device_info_impl.h
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  docs/tests/test_streaming_config.cpp
  examples/cpp/quick_start/quick_start_full.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
  modules/opcua_client_module/include/opcua_client_module/opcua_client_module_impl.h
  modules/opcua_client_module/src/opcua_client_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_default_config.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
  modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
  shared/libraries/opcuatms/opcuatms_server/src/tms_server.cpp
  shared/libraries/websocket_streaming/src/streaming_client.cpp
  shared/libraries/websocket_streaming/src/websocket_streaming_server.cpp
Labels: bug, enhancement

#765 Update version bump script for release candidate version type
  CMakeLists.txt
  docs/Antora-specs/antora.yml
  docs/Antora/antora.yml
  opendaq_version
  opendaq_version_bump.py
Labels: enhancement

#767 Release candidate and development versioning fix
  opendaq_version
  opendaq_version_bump.py
Labels: enhancement

#770 Fix version extraction in `reusable_nuget_creation_and_test.yml`
  .github/workflows/reusable_nuget_creation_and_test.yml
Labels: bug, ci

#766 Initial set of Antora docs improvements
  core/coreobjects/include/coreobjects/property_object.h
  docs/Antora/modules/getting_started/pages/quick_start_application.adoc
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_cpp.adoc
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_csharp.adoc
  docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
  docs/Antora/modules/glossary/pages/glossary.adoc
  docs/Antora/modules/howto_guides/nav-howto-guides.adoc
  docs/Antora/modules/howto_guides/pages/howto.adoc
  docs/Antora/modules/howto_guides/pages/howto_access_control_connect.adoc
  docs/Antora/modules/howto_guides/pages/howto_access_control_introduction.adoc
  docs/Antora/modules/howto_guides/pages/howto_access_control_protected_object.adoc
  docs/Antora/modules/howto_guides/pages/howto_access_control_user_list.adoc
  docs/Antora/modules/howto_guides/pages/howto_add_function_block.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_function_block.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_instance.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_instance_providers.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_streaming.adoc
  docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
  docs/Antora/modules/howto_guides/pages/howto_measure_single_value.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_aligned_signals.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_last_n_samples.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_domain.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timeouts.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timestamps.adoc
  docs/Antora/modules/howto_guides/pages/howto_save_load_configuration.adoc
  docs/Antora/modules/howto_guides/pages/howto_vbox_simulator.adoc
  docs/Antora/modules/knowledge_base/nav-knowledge_base.adoc
  docs/Antora/modules/knowledge_base/pages/modules.adoc
Labels: documentation

#774 Partial High-Performance WebSocket Streaming Server Module fixes
  modules/new_websocket_streaming_server_module/include/httpparser/httprequestparser.h
  modules/new_websocket_streaming_server_module/src/CMakeLists.txt
Labels: bug

#773 `hasProperty` extension for nested property object paths
  changelog/changelog_3.10-3.20.md
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/tests/test_property_object.cpp
  core/opendaq/functionblock/src/function_block_wrapper_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
Labels: enhancement

#776 Fixing restoring struct fields while loading configuration
  changelog/changelog_3.10-3.20.md
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/opendaq/opendaq/mocks/mock_physical_device.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
Labels: bug

#771 Improving device operation mode
  bindings/python/core_objects/generated/py_permission_manager.cpp
  bindings/python/opendaq/generated/component/py_component.cpp
  bindings/python/opendaq/generated/device/py_device.cpp
  bindings/python/opendaq/generated/device/py_network_interface.cpp
  changelog/changelog_3.10-3.20.md
  core/coreobjects/include/coreobjects/core_event_args_ids.h
  core/coreobjects/tests/test_property.cpp
  core/opendaq/component/include/opendaq/component.h
  core/opendaq/component/include/opendaq/component_factory.h
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/include/opendaq/folder_impl.h
  core/opendaq/component/tests/test_folder.cpp
  core/opendaq/device/include/opendaq/address_info.h
  core/opendaq/device/include/opendaq/device.h
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/tests/test_device.cpp
  core/opendaq/functionblock/include/opendaq/function_block_impl.h
  core/opendaq/opendaq/include/opendaq/instance_impl.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/component.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/device.h
  core/opendaq/opendaq/mocks/include/opendaq/gmock/signal.h
  core/opendaq/opendaq/mocks/include/opendaq/mock/mock_physical_device.h
  core/opendaq/opendaq/mocks/mock_physical_device.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
  core/opendaq/reader/include/opendaq/reader_status.h
  examples/cpp/quick_start/quick_start_empty.cpp
  modules/ref_device_module/include/ref_device_module/ref_can_channel_impl.h
  modules/ref_device_module/include/ref_device_module/ref_channel_impl.h
  modules/ref_device_module/include/ref_device_module/ref_device_impl.h
  modules/ref_device_module/src/ref_can_channel_impl.cpp
  modules/ref_device_module/src/ref_channel_impl.cpp
  modules/ref_device_module/src/ref_device_impl.cpp
  modules/ref_device_module/src/ref_device_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_helpers/test_helpers.h
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/include/config_protocol/config_server_device.h
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_device_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_device.cpp
  shared/libraries/websocket_streaming/tests/test_signal_descriptor_converter.cpp
Labels: bug

#778 Fixing remote calling function with enumeration
  changelog/changelog_3.10-3.20.md
  core/coretypes/include/coretypes/struct_impl.h
  core/coretypes/src/enumeration_impl.cpp
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/src/config_protocol_client.cpp
Labels: bug

#775 Antora: Divio System
  docs/Antora/antora.yml
  docs/Antora/modules/ROOT/pages/introduction.adoc
  docs/Antora/modules/ROOT/pages/playground.adoc
  docs/Antora/modules/explanations/images/datapath1.svg
  docs/Antora/modules/explanations/images/datapath2.svg
  docs/Antora/modules/explanations/images/datapath3.svg
  docs/Antora/modules/explanations/images/device_advanced.svg
  docs/Antora/modules/explanations/images/device_simple.svg
  docs/Antora/modules/explanations/images/functionblocks1.svg
  docs/Antora/modules/explanations/images/functionblocks2.svg
  docs/Antora/modules/explanations/images/functionblocks3.svg
  docs/Antora/modules/explanations/nav-explanations.adoc
  docs/Antora/modules/explanations/pages/components.adoc
  docs/Antora/modules/explanations/pages/data_path.adoc
  docs/Antora/modules/explanations/pages/device.adoc
  docs/Antora/modules/explanations/pages/eval_value.adoc
  docs/Antora/modules/explanations/pages/explanations.adoc
  docs/Antora/modules/explanations/pages/function_blocks.adoc
  docs/Antora/modules/explanations/pages/glossary.adoc
  docs/Antora/modules/explanations/pages/interfaces_objects_wrappers.adoc
  docs/Antora/modules/explanations/pages/modules.adoc
  docs/Antora/modules/explanations/pages/multireader_spec.adoc
  docs/Antora/modules/explanations/pages/opendaq_architecture.adoc
  docs/Antora/modules/explanations/pages/packets.adoc
  docs/Antora/modules/explanations/pages/property_system.adoc
  docs/Antora/modules/explanations/pages/protocol_features_characteristics.adoc
  docs/Antora/modules/explanations/pages/readers.adoc
  docs/Antora/modules/explanations/pages/signals.adoc
  docs/Antora/modules/explanations/pages/streaming.adoc
  docs/Antora/modules/glossary/nav-glossary.adoc
  docs/Antora/modules/howto_guides/pages/howto_add_function_block.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_function_block.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_instance.adoc
  docs/Antora/modules/howto_guides/pages/howto_configure_streaming.adoc
  docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
  docs/Antora/modules/howto_guides/pages/howto_measure_single_value.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_aligned_signals.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_last_n_samples.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_domain.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timeouts.adoc
  docs/Antora/modules/howto_guides/pages/howto_read_with_timestamps.adoc
  docs/Antora/modules/howto_guides/pages/howto_save_load_configuration.adoc
  docs/Antora/modules/howto_guides/pages/howto_vbox_simulator.adoc
  docs/Antora/modules/reference/nav-reference.adoc
  docs/Antora/modules/tutorials/images/function-block-types.svg
  docs/Antora/modules/tutorials/images/renderer.PNG
  docs/Antora/modules/tutorials/images/signal-path.svg
  docs/Antora/modules/tutorials/pages/quick_start.adoc
  docs/Antora/modules/tutorials/pages/quick_start_building_opendaq.adoc
  docs/Antora/modules/tutorials/pages/quick_start_setting_up_cpp.adoc
  docs/Antora/modules/tutorials/pages/quick_start_setting_up_csharp.adoc
  docs/Antora/modules/tutorials/pages/quick_start_setting_up_python.adoc
  docs/Antora/modules/tutorials/pages/tutorial_application.adoc
  docs/Antora/modules/tutorials/tutorials.adoc
Labels: documentation, enhancement

#734 [TBBAS-2132] Config objects are not saved/loaded from JSON
  bindings/python/opendaq/generated/component/py_component_private.cpp
  changelog/changelog_3.10-3.20.md
  core/coretypes/include/coretypes/validation.h
  core/coretypes/tests/test_errorinfo.cpp
  core/opendaq/component/include/opendaq/component_impl.h
  core/opendaq/component/include/opendaq/component_private.h
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/include/opendaq/device_info_config.h
  core/opendaq/functionblock/include/opendaq/function_block_impl.h
  core/opendaq/logger/src/logger_impl.cpp
  core/opendaq/modulemanager/include/opendaq/module_impl.h
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/include/opendaq/module_manager_utils.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/opendaq/mocks/mock_device_module.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
  core/opendaq/signal/include/opendaq/signal_container_impl.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  core/opendaq/streaming/include/opendaq/mirrored_device_impl.h
  core/opendaq/streaming/include/opendaq/streaming_source_manager.h
  core/opendaq/streaming/include/opendaq/streaming_type.h
  core/opendaq/streaming/src/CMakeLists.txt
  core/opendaq/utility/include/opendaq/mem_pool_allocator.h
  core/opendaq/utility/tests/test_mem_pool_allocator.cpp
  modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
  modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h
  modules/native_streaming_client_module/src/native_device_impl.cpp
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/tests/test_opendaq_device_modules/test_default_config.cpp
  modules/tests/test_opendaq_device_modules/test_helpers/test_helpers.h
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_subdevices.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_client_folder_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol.h
  shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
  shared/libraries/config_protocol/include/config_protocol/config_server_component.h
  shared/libraries/config_protocol/src/config_protocol_client.cpp
  shared/libraries/config_protocol/src/config_protocol_server.cpp
  shared/libraries/opcuatms/opcuatms/src/converters/property_object_conversion_utils.cpp
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_component_impl.h
  shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_device_impl.h
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_component_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
  shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_function_block_impl.cpp
  shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/objects/tms_server_component.h
  shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_device.cpp
Labels: bug

#764 Support restoring device info fields
  changelog/changelog_3.10-3.20.md
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/opendaq/device/include/opendaq/device_impl.h
  core/opendaq/device/include/opendaq/device_info_impl.h
  core/opendaq/opendaq/tests/test_core_events.cpp
  core/opendaq/opendaq/tests/test_instance.cpp
  core/opendaq/signal/include/opendaq/signal_container_impl.h
  modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_device_info_impl.h
  shared/libraries/opcuatms/opcuatms/src/converters/property_object_conversion_utils.cpp
Labels: enhancement

#780 Make RatioPtr.simplify const function
  core/coretypes/include/coretypes/ratio_ptr.h
Labels: enhancement
