Repository openDAQ/openDAQ, pull requests merged in 2025-08, with the labels that each got.

#752 Fix switch in EvalValue decoding the default value wrong
  core/coreobjects/src/eval_nodes.cpp
Labels: bug

#873 C bindings: examples and tutorials
  docs/Antora/modules/tutorials/pages/tutorial_application.adoc
  examples/CMakeLists.txt
  examples/c/.gitignore
  examples/c/CMakeLists.txt
  examples/c/application_empty.c
  examples/c/application_tutorial.c
Labels: documentation, enhancement, bindings:c

#882 Fix missing property args header installation
  changelog/changelog_3.20-3.30.md
  core/coreobjects/src/CMakeLists.txt
Labels: bug

#881 [TBBAS-2480] Python bindings: update generation with new edge cases
  bindings/python/core_types/generated/py_struct_builder.cpp
  bindings/python/core_types/generated/py_struct_type.cpp
  bindings/python/opendaq/generated/device/py_device.cpp
  bindings/python/opendaq/generated/modulemanager/py_module.cpp
  bindings/python/opendaq/generated/reader/py_multi_reader_builder.cpp
  bindings/python/opendaq/generated/signal/py_data_packet.cpp
  bindings/python/opendaq/generated/signal/py_signal_config.cpp
  bindings/python/tests/test_how_to_last_value.py
  bindings/python/tests/test_reader_datetime.py
  shared/tools/RTGen/bin/RTGen.Python.dll
  shared/tools/RTGen/src/project/RTGen.Python/Generators/PythonGenerator.cs
Labels: bug, bindings:python
