Repository openDAQ/openDAQ, pull requests merged in 2025-02, with the labels that each got.

#691 Fix CMake compile definitions for simulator build
  modules/CMakeLists.txt
Labels: bug

#689 Mdns discovering multiple devices with the same ip
  changelog/changelog_3.0.0-4.0.0.md
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
  shared/libraries/discovery/src/daq_discovery_client.cpp
  shared/libraries/discovery_server/include/discovery_server/mdnsdiscovery_server.h
  shared/libraries/discovery_server/src/mdnsdiscovery_server.cpp
Labels: bug

#690 [TBBAS-1948] Python bindings: MacOS Wheels
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/package.yml
  CMakeLists.txt
  bindings/python/package/build_pip.py
  bindings/python/py_opendaq_daq/CMakeLists.txt
  cmake/openDAQUtils.cmake
  modules/ref_fb_module/tests/test_ref_fb_module.cpp
  modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
Labels: enhancement, bindings:python

#693 Install missing CMake utilities
  CMakeLists.txt
  cmake/openDAQConfig.cmake.in
  cmake/openDAQUtils.cmake
Labels: bug

#699 Add additional resolution options to renderer
  modules/ref_fb_module/src/renderer_fb_impl.cpp
Labels: enhancement

#703 Support handling Query Multicast in mDNS
  shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
Labels: bug

#701 [TBBAS-2092] / [TBBAS-2104] .NET Bindings - Hide not applicable functions (no reference-count increment)
  bindings/dotnet/CMakeLists.txt
  bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/openDAQ.Net.CI.Test.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net.NuGet.Test/openDAQ.Net.NuGet.Test.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesBaseObjectTests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/openDAQ.Net.Test.csproj
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coretypes/BaseObject.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coretypes/ListObject.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
  shared/tools/RTGen/bin/RTGen.CSharp.dll
  shared/tools/RTGen/bin/RTGen.Cpp.dll
  shared/tools/RTGen/bin/RTGen.Delphi.dll
  shared/tools/RTGen/bin/RTGen.Library.dll
  shared/tools/RTGen/bin/RTGen.Python.dll
  shared/tools/RTGen/bin/rtgen.exe
  shared/tools/RTGen/src/project/RTGen.CSharp/Generators/CSharpGenerator.cs
Labels: bindings:c#

#705 Fix changelog formatting
  changelog/changelog_3.10-3.20.md
Labels: enhancement

#696 Fix LT streaming issues
  .github/workflows/package.yml
  external/streaming_protocol/CMakeLists.txt
  opendaq_version
  shared/libraries/websocket_streaming/include/websocket_streaming/input_signal.h
  shared/libraries/websocket_streaming/src/input_signal.cpp
  shared/libraries/websocket_streaming/src/output_signal.cpp
  shared/libraries/websocket_streaming/src/signal_descriptor_converter.cpp
  shared/libraries/websocket_streaming/src/streaming_client.cpp
  shared/libraries/websocket_streaming/tests/test_signal_descriptor_converter.cpp
  shared/libraries/websocket_streaming/tests/test_streaming.cpp
Labels: bug

#714 Permission manager optimizations
  core/coreobjects/include/coreobjects/permissions_builder_impl.h
  core/coreobjects/include/coreobjects/permissions_impl.h
  core/coreobjects/include/coreobjects/property_impl.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coreobjects/src/permission_manager_impl.cpp
  core/coreobjects/src/permissions_builder_impl.cpp
  core/coreobjects/src/permissions_impl.cpp
  core/opendaq/component/include/opendaq/component_impl.h
Labels: enhancement

#702 Native streaming performance optimization
  docs/tests/test_modules.cpp
  modules/native_streaming_server_module/include/native_streaming_server_module/native_streaming_server_impl.h
  modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
  modules/native_streaming_server_module/tests/test_native_streaming_server_module.cpp
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h
  shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h
  shared/libraries/native_streaming_protocol/src/base_session_handler.cpp
  shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
  shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
  shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
  shared/libraries/packet_streaming/include/packet_streaming/packet_streaming_server.h
  shared/libraries/packet_streaming/src/packet_streaming_server.cpp
Labels: enhancement

#715 Update changelog since 3.10
  changelog/changelog_3.10-3.20.md
Labels: documentation
