Repository openDAQ/openDAQ, pull requests merged in 2025-09, with the labels that each got.

#891 [TBBAS-2555] Upgrade nlohmann-json 3.10.2 To 3.11.3
  external/nlohmann_json/CMakeLists.txt
  external/streaming_protocol/CMakeLists.txt
  shared/libraries/websocket_streaming/include/websocket_streaming/signal_descriptor_converter.h
  shared/libraries/websocket_streaming/src/signal_descriptor_converter.cpp
Labels: enhancement

#877 [TBBAS-2107] .NET Bindings - Supplement, improve or add C# examples in the documentation
  bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/OpenDAQ_CITests.cs
  bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqExplanationsTests.cs
  docs/Antora/modules/explanations/pages/multireader_spec.adoc
  docs/Antora/modules/explanations/pages/property_system.adoc
  docs/Antora/modules/explanations/pages/readers.adoc
Labels: documentation, bindings:c#

#895 Add support for --version and __version__ to python package
  bindings/python/package/build_pip.py
  bindings/python/package/opendaq/__init__.py
  examples/applications/python/GUI Application/gui_demo.py
Labels: enhancement

#884 Feature/licensing - tampering check interface
  bindings/python/opendaq/CMakeLists.txt
  bindings/python/opendaq/generated/modulemanager/py_module.cpp
  bindings/python/opendaq/generated/modulemanager/py_module_manager.cpp
  bindings/python/opendaq/generated/opendaq/py_instance_builder.cpp
  bindings/python/opendaq/generated/opendaq/py_module_authenticator.cpp
  bindings/python/opendaq/include/py_opendaq/py_opendaq.h
  bindings/python/opendaq/py_opendaq.cpp
  bindings/python/run_rtgen.sh
  changelog/changelog_3.20-3.30.md
  core/opendaq/modulemanager/include/opendaq/module.h
  core/opendaq/modulemanager/include/opendaq/module_manager.h
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  core/opendaq/modulemanager/tests/CMakeLists.txt
  core/opendaq/modulemanager/tests/mock/CMakeLists.txt
  core/opendaq/modulemanager/tests/mock/mock_module_authenticator.cpp
  core/opendaq/modulemanager/tests/mock/mock_module_authenticator.h
  core/opendaq/modulemanager/tests/test_module_manager_internals.cpp
  core/opendaq/opendaq/include/opendaq/instance_builder.h
  core/opendaq/opendaq/include/opendaq/instance_builder_impl.h
  core/opendaq/opendaq/include/opendaq/module_authenticator.h
  core/opendaq/opendaq/include/opendaq/module_authenticator_impl.h
  core/opendaq/opendaq/include/opendaq/opendaq.h
  core/opendaq/opendaq/src/CMakeLists.txt
  core/opendaq/opendaq/src/instance_builder_impl.cpp
  core/opendaq/opendaq/src/instance_impl.cpp
  examples/applications/cpp/licensing_example/CMakeLists.txt
  examples/applications/cpp/licensing_example/Certificate.txt
  examples/applications/cpp/licensing_example/licensing_example.cpp
  examples/modules/licensing_module/src/licensing_module_impl.cpp
Labels: enhancement

#899 Revert py_device.cpp: operation_mode getter
  bindings/python/opendaq/generated/device/py_device.cpp
Labels: bug, bindings:python

#898 Fix installation (`mutex_impl.h` and `module_authenticator_impl.h`)
  core/coreobjects/src/CMakeLists.txt
  core/opendaq/opendaq/src/CMakeLists.txt
Labels: bug

#869 Implementing video player function block
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/package.yml
  CMakeLists.txt
  changelog/changelog_3.20-3.30.md
  core/opendaq/reader/include/opendaq/time_reader.h
  core/opendaq/signal/include/opendaq/signal_impl.h
  examples/applications/cpp/CMakeLists.txt
  examples/modules/licensing_module/src/license_checker_impl.cpp
  examples/modules/licensing_module/src/licensing_module_impl.cpp
  examples/modules/ref_fb_module/include/ref_fb_module/video_player_fb_impl.h
  examples/modules/ref_fb_module/src/CMakeLists.txt
  examples/modules/ref_fb_module/src/ref_fb_module_impl.cpp
  examples/modules/ref_fb_module/src/video_player_fb_impl.cpp
  examples/modules/ref_fb_module/tests/test_ref_fb_module.cpp
  external/CMakeLists.txt
  tests/integration/test_opendaq_device_modules/test_opcua_device_modules.cpp
Labels: enhancement

#910 Install NSIS on RC branch
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/package.yml
Labels: ci

#918 Custom file logger sinks python example
  examples/applications/python/Integration Examples/custom_file_logger_sinks.py
Labels: documentation

#908 Add support for Intel-LLVM compiler
  .github/workflows/ci.yml
  CMakeBasePresets.json
  CMakeLists.txt
  changelog/changelog_3.20-3.30.md
  core/corecontainers/src/listobject_impl.cpp
  core/coreobjects/include/coreobjects/property_impl.h
  core/coreobjects/include/coreobjects/property_object_impl.h
  core/coretypes/include/coretypes/intfs.h
  core/opendaq/reader/src/signal_reader.cpp
  examples/modules/audio_device_module/tests/test_fb_wav_reader.cpp
  examples/modules/ref_device_module/include/ref_device_module/ref_can_channel_impl.h
  examples/modules/ref_device_module/include/ref_device_module/ref_channel_impl.h
  examples/modules/ref_device_module/src/ref_can_channel_impl.cpp
  examples/modules/ref_fb_module/include/ref_fb_module/power_reader_fb_impl.h
  examples/modules/ref_fb_module/include/ref_fb_module/renderer_fb_impl.h
  examples/modules/ref_fb_module/src/renderer_fb_impl.cpp
  external/CMakeLists.txt
  external/taskflow/CMakeLists.txt
  external/taskflow/patches/0004-IntelLLVM-Support.patch
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
  shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_integration.cpp
  shared/libraries/packet_streaming/src/packet_streaming_client.cpp
  shared/libraries/websocket_streaming/src/streaming_server.cpp
Labels: enhancement

#925 DNS resolution fixes / Multi-network adapter device support
  changelog/changelog_3.20-3.30.md
  core/opendaq/device/include/opendaq/server_capability_impl.h
  core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
  core/opendaq/modulemanager/src/module_manager_impl.cpp
  external/mdns/CMakeLists.txt
  external/mdns/patches/0001-Multicast-commands-ip6-ifindex.patch
  external/mdns/patches/0002-Fix-warnings.patch
  modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
  modules/opcua_client_module/src/opcua_client_module_impl.cpp
  modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
  shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
  shared/libraries/discovery/src/daq_discovery_client.cpp
  shared/libraries/discovery_server/include/discovery_server/mdnsdiscovery_server.h
  shared/libraries/discovery_server/src/mdnsdiscovery_server.cpp
  tests/integration/test_opendaq_device_modules/test_native_device_modules.cpp
  tests/integration/test_opendaq_device_modules/test_native_streaming_modules.cpp
  tests/integration/test_opendaq_device_modules/test_opcua_device_modules.cpp
  tests/integration/test_opendaq_device_modules/test_websocket_modules.cpp
Labels: bug, enhancement
